<?php
if (!defined('ABSPATH')) exit;
final class GDCP_Assignment_Service {
    public function for_project($id){ return gdcp_assignment_repository()->for_project($id); }
    public function workload($tenant,$limit=100){ $rows=gdcp_assignment_repository()->for_tenant_workload($tenant,$limit); foreach($rows as $row)$row->user=gd_client_portal_cached_user($row->user_id); return $rows; }
    public function assign($project_id,$user_id,$role='member'){ $project=gd_client_portal_cached_project($project_id); if(!$project||!gd_client_portal_verify_project_access($project)||!(current_user_can('manage_options')||gd_client_portal_user_is_tenant_admin()))return false; $user=gd_client_portal_cached_user($user_id); if(!$user||user_can($user,'manage_options'))return false; $tenant=absint(get_user_meta($user_id,'gd_client_portal_tenant_id',true)); if(!$tenant||$tenant!==absint($project->tenant_id))return false; $role=in_array($role,array('lead','member'),true)?$role:'member'; if($role==='lead')gdcp_assignment_repository()->demote_leads($project_id); $ok=gdcp_assignment_repository()->replace(array('project_id'=>absint($project_id),'tenant_id'=>absint($project->tenant_id),'user_id'=>absint($user_id),'assignment_role'=>$role,'assigned_by'=>gd_client_portal_cached_current_user_id())); if($ok&&function_exists('gd_client_portal_create_notification'))gd_client_portal_create_notification($user_id,__('Project assigned to you','gd-client-portal'),sprintf(__('You have been assigned to project “%s”.','gd-client-portal'),$project->title),'assignment',$project->id,$project->tenant_id); if($ok)do_action('gd_client_portal_project_assigned',$project->id,$user_id,$role); return $ok; }
    public function remove($project_id,$user_id){ $project=gd_client_portal_cached_project($project_id); if(!$project||!gd_client_portal_verify_project_access($project)||!(current_user_can('manage_options')||gd_client_portal_user_is_tenant_admin()))return false; return gdcp_assignment_repository()->delete($project_id,$user_id); }
}
function gdcp_assignment_service(){ static $s; if(!$s)$s=new GDCP_Assignment_Service(); return $s; }
