<?php
if (!defined('ABSPATH')) exit;
final class GDCP_Automation_Service {
    private $repo; public function __construct(){ $this->repo=new GDCP_Automation_Repository(); }
    public function get_rule($id){return $this->repo->get_rule($id);} public function list_rules($status=''){return $this->repo->list_rules($status);} public function create_rule($data){return $this->repo->create_rule($data);} public function update_rule($id,$data){return $this->repo->update_rule($id,$data);} public function delete_rule($id){return $this->repo->delete_rule($id);} public function increment_run($id,$when){return $this->repo->increment_run($id,$when);} public function get_template($id){return $this->repo->get_template($id);} public function list_templates($limit=20){return $this->repo->list_templates($limit);} public function create_template($data){return $this->repo->create_template($data);} public function list_logs($limit=25){return $this->repo->list_logs($limit);} public function create_log($data){return $this->repo->create_log($data);} public function list_queue($limit=100){return $this->repo->list_queue($limit);} public function get_queue($id){return $this->repo->get_queue($id);} public function create_queue($data){return $this->repo->create_queue($data);} public function update_queue($id,$data,$extra=array()){return $this->repo->update_queue($id,$data,$extra);} public function set_rule_status($id,$status){$status=sanitize_key($status);if(!in_array($status,array('active','paused'),true))return false;return $this->repo->update_rule($id,array('status'=>$status,'updated_at'=>current_time('mysql')));}
    public function import_rule($data,$created_by=0){$data=is_array($data)?$data:array();if(empty($data['actions']))return 0;return $this->repo->create_rule(array('name'=>sanitize_text_field($data['name']??'Imported workflow'),'event_key'=>sanitize_key($data['event_key']??'daily'),'conditions'=>wp_json_encode($data['conditions']??array()),'actions'=>wp_json_encode($data['actions']),'status'=>'paused','created_by'=>absint($created_by),'created_at'=>current_time('mysql'),'updated_at'=>current_time('mysql')));}
    public function restore_rule($id,$data){$id=absint($id);if(!$id||!is_array($data))return false;$clean=array();foreach(array('name','event_key','conditions','actions') as $k){if(array_key_exists($k,$data))$clean[$k]=$data[$k];}$clean['status']='paused';$clean['updated_at']=current_time('mysql');return $this->repo->update_rule($id,$clean);}
    public function duplicate_rule($id,$created_by=0){$r=$this->repo->get_rule($id);if(!$r)return 0;return $this->repo->create_rule(array('name'=>sanitize_text_field($r->name).' — Copy','event_key'=>sanitize_key($r->event_key),'conditions'=>$r->conditions,'actions'=>$r->actions,'status'=>'paused','created_by'=>absint($created_by),'created_at'=>current_time('mysql'),'updated_at'=>current_time('mysql')));}
    public function list_queue_by_status($statuses,$limit=100){return $this->repo->list_queue_by_status($statuses,$limit);} public function list_queue_for_scope($statuses,$tenant=0,$platform=false,$limit=100){return $this->repo->list_queue_for_scope($statuses,$tenant,$platform,$limit);}
    public function retry_queue($id){return $this->repo->update_queue($id,array('status'=>'queued','run_at'=>current_time('mysql'),'attempts'=>0,'last_error'=>'','locked_at'=>null,'updated_at'=>current_time('mysql')),array('status'=>'failed'));} public function cancel_queue($id){$row=$this->repo->get_queue($id);if(!$row||!in_array((string)$row->status,array('queued','running'),true))return false;return $this->repo->update_queue($id,array('status'=>'cancelled','locked_at'=>null,'updated_at'=>current_time('mysql')));} public function claim_queue($id){return $this->repo->claim_queue($id);} public function stale_queue($limit=50){return $this->repo->stale_queue($limit);} public function due_queue($limit=50){return $this->repo->due_queue($limit);} public function stats(){return $this->repo->stats();} public function analytics($days=30){return $this->repo->analytics($days);} public function event_analytics($days=30){return $this->repo->event_analytics($days);}
}
function gdcp_automation_service(){static $s;if(!$s)$s=new GDCP_Automation_Service();return $s;}
