<?php
/**
 * GD Client Portal v3.6 - Client Collaboration & Team Workspace.
 */
if (!defined('ABSPATH')) exit;

function gd_client_portal_collab_table($suffix) { global $wpdb; return $wpdb->prefix . 'gd_' . $suffix; }
function gd_client_portal_activate_collaboration_tables() {
    global $wpdb; require_once ABSPATH . 'wp-admin/includes/upgrade.php'; $c=$wpdb->get_charset_collate();
    $tasks=gd_client_portal_collab_table('project_tasks');
    $updates=gd_client_portal_collab_table('project_updates');
    $notes=gd_client_portal_collab_table('project_internal_notes');
    dbDelta("CREATE TABLE {$tasks} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, project_id bigint(20) unsigned NOT NULL, tenant_id bigint(20) unsigned NOT NULL DEFAULT 0, title varchar(255) NOT NULL, description text NULL, status varchar(30) NOT NULL DEFAULT 'todo', priority varchar(20) NOT NULL DEFAULT 'normal', assigned_to bigint(20) unsigned NOT NULL DEFAULT 0, due_date datetime NULL, created_by bigint(20) unsigned NOT NULL DEFAULT 0, created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, completed_at datetime NULL, PRIMARY KEY(id), KEY project_id(project_id), KEY tenant_id(tenant_id), KEY assigned_to(assigned_to), KEY status(status), KEY due_date(due_date) ) {$c};");
    dbDelta("CREATE TABLE {$updates} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, project_id bigint(20) unsigned NOT NULL, tenant_id bigint(20) unsigned NOT NULL DEFAULT 0, author_id bigint(20) unsigned NOT NULL DEFAULT 0, visibility varchar(20) NOT NULL DEFAULT 'client', title varchar(255) NOT NULL, body longtext NOT NULL, created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), KEY project_id(project_id), KEY tenant_id(tenant_id), KEY author_id(author_id), KEY visibility(visibility), KEY created_at(created_at) ) {$c};");
    dbDelta("CREATE TABLE {$notes} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, project_id bigint(20) unsigned NOT NULL, tenant_id bigint(20) unsigned NOT NULL DEFAULT 0, author_id bigint(20) unsigned NOT NULL DEFAULT 0, body longtext NOT NULL, created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), KEY project_id(project_id), KEY tenant_id(tenant_id), KEY author_id(author_id), KEY created_at(created_at) ) {$c};");
}
// Schema lifecycle is managed centrally by GDCP_Migration_Manager (v6.8+).

function gd_client_portal_collab_is_manager() { return current_user_can('manage_options') || gd_client_portal_user_is_tenant_admin(); }
function gd_client_portal_collab_project($id) { $p=gd_client_portal_get_project_by_id(absint($id)); return ($p && gd_client_portal_verify_project_access($p)) ? $p : false; }
function gd_client_portal_collab_team($project) { return function_exists('gd_client_portal_get_project_assignments') ? gd_client_portal_get_project_assignments($project->id) : array(); }
function gd_client_portal_collab_statuses() { return array('todo'=>'To do','in_progress'=>'In progress','blocked'=>'Blocked','done'=>'Done'); }
function gd_client_portal_collab_priorities() { return array('low'=>'Low','normal'=>'Normal','high'=>'High','urgent'=>'Urgent'); }

function gd_client_portal_collab_get_tasks($project_id=0,$limit=100) {
    $tenant=0; if(!$project_id && !gd_client_portal_is_platform_admin()) $tenant=absint(gd_client_portal_get_current_tenant_id());
    if(!$project_id && !$tenant)return array();
    return gdcp_collaboration_service()->tasks(absint($project_id),$tenant,$limit);
}
function gd_client_portal_collab_get_updates($project_id=0,$limit=30,$include_internal=false) {
    $tenant=0; if(!$project_id && !gd_client_portal_is_platform_admin()) $tenant=absint(gd_client_portal_get_current_tenant_id());
    if(!$project_id && !$tenant)return array();
    return gdcp_collaboration_service()->updates(absint($project_id),$tenant,$limit,$include_internal);
}
function gd_client_portal_collab_get_notes($project_id) { return gdcp_collaboration_service()->notes(absint($project_id),100); }
function gd_client_portal_collab_notify_mentions($text,$project,$actor_id) {
    if(!function_exists('gd_client_portal_create_notification'))return;
    preg_match_all('/@([A-Za-z0-9._-]{2,60})/',(string)$text,$m); if(empty($m[1]))return;
    foreach(array_unique($m[1]) as $login){$u=get_user_by('login',$login);if(!$u||absint($u->ID)===absint($actor_id))continue;$tid=absint(get_user_meta($u->ID,'gd_client_portal_tenant_id',true));if($tid!==absint($project->tenant_id))continue;gd_client_portal_create_notification($u->ID,__('You were mentioned','gd-client-portal'),sprintf(__('You were mentioned in project “%s”.','gd-client-portal'),$project->title),'mention',$project->id,$project->tenant_id);}
}

function gd_client_portal_collab_task_ajax() {
    if(!is_user_logged_in()||!gd_client_portal_verify_request()||!gd_client_portal_collab_is_manager())wp_send_json_error(array('message'=>__('Permission denied.','gd-client-portal')),403);
    check_ajax_referer('gd_client_portal_collaboration','nonce'); global $wpdb;
    $action=sanitize_key(wp_unslash($_POST['operation']??''));$id=absint($_POST['task_id']??0);$project=gd_client_portal_collab_project($_POST['project_id']??0);
    if($action==='delete'){$task=gdcp_collaboration_service()->task($id);if(!$task||!gd_client_portal_collab_project($task->project_id))wp_send_json_error(array('message'=>'Task access denied.'),403);gdcp_collaboration_service()->delete_task($id);wp_send_json_success(array('message'=>'Task deleted.'));}
    if(!$project)wp_send_json_error(array('message'=>'Project access denied.'),403);
    $statuses=gd_client_portal_collab_statuses();$priorities=gd_client_portal_collab_priorities();$title=sanitize_text_field(wp_unslash($_POST['title']??''));$desc=sanitize_textarea_field(wp_unslash($_POST['description']??''));$status=sanitize_key($_POST['status']??'todo');$priority=sanitize_key($_POST['priority']??'normal');$assignee=absint($_POST['assigned_to']??0);$due=sanitize_text_field(wp_unslash($_POST['due_date']??''));
    if(!isset($statuses[$status]))$status='todo';if(!isset($priorities[$priority]))$priority='normal';
    if($assignee){$u=gd_client_portal_cached_user($assignee);$ut=absint(get_user_meta($assignee,'gd_client_portal_tenant_id',true));if(!$u||$ut!==absint($project->tenant_id)||user_can($u,'manage_options'))$assignee=0;}
    if($action==='create'){if(!$title)wp_send_json_error(array('message'=>'Task title is required.')); $new=gdcp_collaboration_service()->create_task($project,array('title'=>$title,'description'=>$desc,'status'=>$status,'priority'=>$priority,'assigned_to'=>$assignee,'due_date'=>$due?$due.' 23:59:59':null,'created_by'=>gd_client_portal_cached_current_user_id(),'created_at'=>current_time('mysql'),'updated_at'=>current_time('mysql')));if($assignee&&function_exists('gd_client_portal_create_notification'))gd_client_portal_create_notification($assignee,__('New project task','gd-client-portal'),sprintf(__('You were assigned “%s” on %s.','gd-client-portal'),$title,$project->title),'task',$project->id,$project->tenant_id);if(function_exists('gd_client_portal_audit_log'))gd_client_portal_audit_log('task_created',$title,$project->id,$project->tenant_id,$desc,'task',$new,array('assigned_to'=>$assignee));wp_send_json_success(array('message'=>'Task created.','id'=>$new));}
    if($action==='update'){$task=gdcp_collaboration_service()->task($id,$project->id);if(!$task)wp_send_json_error(array('message'=>'Task not found.'),404);$completed=$status==='done'?current_time('mysql'):null;gdcp_collaboration_service()->update_task($id,array('title'=>$title?:$task->title,'description'=>$desc,'status'=>$status,'priority'=>$priority,'assigned_to'=>$assignee,'due_date'=>$due?$due.' 23:59:59':null,'updated_at'=>current_time('mysql'),'completed_at'=>$completed));if($assignee&&$assignee!==(int)$task->assigned_to&&function_exists('gd_client_portal_create_notification'))gd_client_portal_create_notification($assignee,__('Task assigned','gd-client-portal'),sprintf(__('You were assigned “%s” on %s.','gd-client-portal'),$title?:$task->title,$project->title),'task',$project->id,$project->tenant_id);wp_send_json_success(array('message'=>'Task updated.'));}
    wp_send_json_error(array('message'=>'Unknown operation.'));
}
add_action('wp_ajax_gd_client_portal_collab_task','gd_client_portal_collab_task_ajax');

function gd_client_portal_collab_update_ajax() {
    if(!is_user_logged_in()||!gd_client_portal_verify_request())wp_send_json_error(array('message'=>'Access denied.'),403);check_ajax_referer('gd_client_portal_collaboration','nonce');$project=gd_client_portal_collab_project($_POST['project_id']??0);if(!$project)wp_send_json_error(array('message'=>'Project access denied.'),403);$title=sanitize_text_field(wp_unslash($_POST['title']??''));$body=sanitize_textarea_field(wp_unslash($_POST['body']??''));if(!$body)wp_send_json_error(array('message'=>'Update text is required.'));$new=gdcp_collaboration_service()->create_update($project,array('author_id'=>gd_client_portal_cached_current_user_id(),'visibility'=>'client','title'=>$title?:__('Project update','gd-client-portal'),'body'=>$body,'created_at'=>current_time('mysql')));gd_client_portal_collab_notify_mentions($body,$project,gd_client_portal_cached_current_user_id());if(function_exists('gd_client_portal_create_notification')){$owner=absint($project->user_id);if($owner&&$owner!==gd_client_portal_cached_current_user_id())gd_client_portal_create_notification($owner,__('New project update','gd-client-portal'),$title?:__('A new update was posted.','gd-client-portal'),'project_update',$project->id,$project->tenant_id);}if(function_exists('gd_client_portal_audit_log'))gd_client_portal_audit_log('project_update_posted',$title?:'Project update',$project->id,$project->tenant_id,$body,'project_update',$new);wp_send_json_success(array('message'=>'Update posted.'));
}
add_action('wp_ajax_gd_client_portal_collab_update','gd_client_portal_collab_update_ajax');

function gd_client_portal_collab_note_ajax() {
    if(!is_user_logged_in()||!gd_client_portal_verify_request()||!gd_client_portal_collab_is_manager())wp_send_json_error(array('message'=>'Permission denied.'),403);check_ajax_referer('gd_client_portal_collaboration','nonce');$project=gd_client_portal_collab_project($_POST['project_id']??0);if(!$project)wp_send_json_error(array('message'=>'Project access denied.'),403);$body=sanitize_textarea_field(wp_unslash($_POST['body']??''));if(!$body)wp_send_json_error(array('message'=>'Note cannot be empty.'));$new=gdcp_collaboration_service()->create_note($project,array('author_id'=>gd_client_portal_cached_current_user_id(),'body'=>$body,'created_at'=>current_time('mysql'),'updated_at'=>current_time('mysql')));if(function_exists('gd_client_portal_audit_log'))gd_client_portal_audit_log('internal_note_added',__('Internal note added','gd-client-portal'),$project->id,$project->tenant_id,$body,'internal_note',$new);wp_send_json_success(array('message'=>'Internal note saved.'));
}
add_action('wp_ajax_gd_client_portal_collab_note','gd_client_portal_collab_note_ajax');

function gd_client_portal_render_collaboration($atts=array()) {
    if(!gd_client_portal_verify_request())return gd_client_portal_render_access_gate(__('Team Workspace','gd-client-portal'),__('Please sign in to collaborate on projects.','gd-client-portal'));
    wp_enqueue_style('gd-client-portal-collaboration');wp_enqueue_style('gdcp-collaboration-approvals-ux');wp_enqueue_script('gd-client-portal-collaboration');$project_id=absint($_GET['collab_project']??$_GET['project_id']??0);$projects=gd_client_portal_get_visible_projects();$project=$project_id?gd_client_portal_collab_project($project_id):false;$nonce=wp_create_nonce('gd_client_portal_collaboration');
    ob_start();echo '<div class="gd-collab" data-nonce="'.esc_attr($nonce).'">';
    if(!$project){echo '<div class="gd-collab-hero"><div><span>CLIENT PORTAL · V3.6</span><h2>Collaboration Workspace</h2><p>Coordinate tasks, team assignments, project updates and client-visible progress in one place.</p></div></div><div class="gd-collab-projects">';foreach($projects as $p)echo '<a class="gd-collab-project" href="'.esc_url(add_query_arg('collab_project',$p->id,get_permalink())).'"><strong>'.esc_html($p->title).'</strong><span>'.esc_html(ucwords(str_replace('_',' ',$p->current_stage))).' · '.intval($p->progress).'%</span></a>';if(!$projects)echo '<div class="gd-collab-empty">No accessible projects.</div>';echo '</div></div>';return ob_get_clean();}
    $tasks=gd_client_portal_collab_get_tasks($project->id);$updates=gd_client_portal_collab_get_updates($project->id,30);$notes=gd_client_portal_collab_get_notes($project->id);$team=gd_client_portal_collab_team($project);$manager=gd_client_portal_collab_is_manager();$statuses=gd_client_portal_collab_statuses();$priorities=gd_client_portal_collab_priorities();
    echo '<div class="gd-collab-hero"><div><a href="'.esc_url(remove_query_arg('collab_project')).'">← All projects</a><span>PROJECT COLLABORATION</span><h2>'.esc_html($project->title).'</h2><p>Coordinate work, keep clients informed, and move the project toward review.</p></div><div class="gd-collab-progress"><strong>'.intval($project->progress).'%</strong><small>complete</small></div></div>';
    $task_total=count($tasks);$task_done=count(array_filter($tasks,function($t){return $t->status==='done';}));
    echo '<div class="gd-collab-workflow-summary"><div class="gd-collab-workflow-summary__item"><span class="gd-collab-workflow-summary__label">Current stage</span><span class="gd-collab-workflow-summary__value">'.esc_html(ucwords(str_replace('_',' ',$project->current_stage))).'</span></div><div class="gd-collab-workflow-summary__item"><span class="gd-collab-workflow-summary__label">Tasks completed</span><span class="gd-collab-workflow-summary__value">'.intval($task_done).' / '.intval($task_total).'</span></div><div class="gd-collab-workflow-summary__item"><span class="gd-collab-workflow-summary__label">Client updates</span><span class="gd-collab-workflow-summary__value">'.intval(count($updates)).'</span></div><div class="gd-collab-workflow-summary__item"><span class="gd-collab-workflow-summary__label">Next workflow focus</span><span class="gd-collab-workflow-summary__value">'.esc_html($project->current_stage==='approval'?'Client review':'Project delivery').'</span></div></div><div class="gd-collab-tabs"><button class="is-active" data-tab="board">Task board</button><button data-tab="updates">Updates</button><button data-tab="discussion">Discussion</button>'.($manager?'<button data-tab="internal">Internal notes</button>':'').'</div>';
    echo '<section class="gd-collab-panel is-active" data-panel="board"><div class="gd-collab-panel-head"><div><h3>Task board</h3><p>Assign work, set priorities and track delivery.</p></div>'.($manager?'<button class="gd-collab-primary" id="gd-collab-new-task">+ New task</button>':'').'</div><div id="gd-collab-task-form" class="gd-collab-form" hidden><div class="gd-collab-grid"><input id="gd-task-title" placeholder="Task title"><select id="gd-task-priority">'.implode('',array_map(function($k,$v){return '<option value="'.esc_attr($k).'">'.esc_html($v).' priority</option>';},array_keys($priorities),$priorities)).'</select><select id="gd-task-assignee"><option value="0">Unassigned</option>'.implode('',array_map(function($a){$u=gd_client_portal_cached_user($a->user_id);return '<option value="'.intval($a->user_id).'">'.esc_html($u?$u->display_name:'User #'.$a->user_id).'</option>';},$team)).'</select><input type="date" id="gd-task-due"></div><textarea id="gd-task-description" placeholder="Task details..."></textarea><button id="gd-task-save" class="gd-collab-primary">Create task</button><span id="gd-task-result"></span></div><div class="gd-collab-kanban">';foreach($statuses as $sk=>$sv){echo '<div class="gd-collab-column"><h4>'.esc_html($sv).'<span>'.count(array_filter($tasks,function($t)use($sk){return $t->status===$sk;})).'</span></h4>';foreach($tasks as $t){if($t->status!==$sk)continue;$u=$t->assigned_to?gd_client_portal_cached_user($t->assigned_to):false;echo '<article class="gd-task-card"><div><span class="gd-task-priority priority-'.esc_attr($t->priority).'">'.esc_html(ucfirst($t->priority)).'</span>'.($t->due_date?'<time>'.esc_html(wp_date(get_option('date_format'),strtotime($t->due_date))).'</time>':'').'</div><strong>'.esc_html($t->title).'</strong><p>'.esc_html(wp_trim_words($t->description,18)).'</p><small>'.esc_html($u?$u->display_name:'Unassigned').'</small>';if($manager)echo '<div class="gd-task-actions"><button data-task-action="edit" data-task-id="'.intval($t->id).'">Edit</button><button data-task-action="done" data-task-id="'.intval($t->id).'">'.($t->status==='done'?'Reopen':'Done').'</button></div>';echo '</article>';}echo '</div>';};echo '</div></section>';
    echo '<section class="gd-collab-panel" data-panel="updates"><div class="gd-collab-panel-head"><div><h3>Client-visible updates</h3><p>Keep the client informed without exposing internal notes.</p></div></div>'.($manager?'<div class="gd-collab-form"><input id="gd-update-title" placeholder="Update title"><textarea id="gd-update-body" placeholder="Share a project update… Use @username to mention a team member."></textarea><button id="gd-update-save" class="gd-collab-primary">Post update</button><span id="gd-update-result"></span></div>':'');echo '<div class="gd-collab-feed">';foreach($updates as $u){$a=gd_client_portal_cached_user($u->author_id);echo '<article><div class="gd-feed-meta"><strong>'.esc_html($a?$a->display_name:'Portal user').'</strong><time>'.esc_html(wp_date(get_option('date_format').' '.get_option('time_format'),strtotime($u->created_at))).'</time></div><h4>'.esc_html($u->title).'</h4><p>'.nl2br(esc_html($u->body)).'</p></article>';}if(!$updates)echo '<div class="gd-collab-empty">No project updates yet.</div>';echo '</div></section>';
    echo '<section class="gd-collab-panel" data-panel="discussion"><div class="gd-collab-panel-head"><div><h3>Project discussion</h3><p>Continue the existing secure project conversation below.</p></div></div>';if(function_exists('gd_client_portal_render_project_workspace'))echo '<div class="gd-collab-message-note">Use the Project Workspace message composer to send full conversation messages and attachments.</div><a class="gd-collab-primary inline" href="'.esc_url(add_query_arg('project_id',$project->id,get_permalink())).'">Open project conversation →</a>';echo '</section>';
    if($manager){echo '<section class="gd-collab-panel" data-panel="internal"><div class="gd-collab-panel-head"><div><h3>Internal notes</h3><p>Private notes visible only to authorized project managers.</p></div></div><div class="gd-collab-form"><textarea id="gd-note-body" placeholder="Private team note…"></textarea><button id="gd-note-save" class="gd-collab-primary">Save internal note</button><span id="gd-note-result"></span></div><div class="gd-collab-feed internal">';foreach($notes as $n){$a=gd_client_portal_cached_user($n->author_id);echo '<article><div class="gd-feed-meta"><strong>'.esc_html($a?$a->display_name:'Portal user').'</strong><time>'.esc_html($n->created_at).'</time></div><p>'.nl2br(esc_html($n->body)).'</p></article>';}if(!$notes)echo '<div class="gd-collab-empty">No internal notes.</div>';echo '</div></section>';}
    echo '</div>';return ob_get_clean();
}
add_shortcode('gd_collaboration','gd_client_portal_render_collaboration');add_shortcode('gd_team_workspace','gd_client_portal_render_collaboration');
add_action('init',function(){if(function_exists('gd_client_portal_register_dashboard_view'))gd_client_portal_register_dashboard_view('collaboration','gd_client_portal_render_collaboration');});

function gd_client_portal_collaboration_admin(){if(!gd_client_portal_user_can_access_admin())wp_die('Access denied.');$projects=gd_client_portal_get_visible_projects();echo '<div class="wrap gd-collab-admin"><h1>Collaboration Workspace</h1><p>Open a project to manage tasks, updates and internal collaboration.</p><table class="widefat striped"><thead><tr><th>Project</th><th>Stage</th><th>Progress</th><th>Tasks</th><th>Team lead</th><th>Open</th></tr></thead><tbody>';foreach($projects as $p){$tasks=gd_client_portal_collab_get_tasks($p->id);$lead=function_exists('gd_client_portal_get_project_lead')?gd_client_portal_get_project_lead($p->id):false;$u=$lead?gd_client_portal_cached_user($lead->user_id):false;echo '<tr><td><strong>'.esc_html($p->title).'</strong><br>#'.intval($p->id).'</td><td>'.esc_html(ucwords(str_replace('_',' ',$p->current_stage))).'</td><td>'.intval($p->progress).'%</td><td>'.intval(count($tasks)).'</td><td>'.esc_html($u?$u->display_name:'Unassigned').'</td><td><a class="button button-primary" href="'.esc_url(add_query_arg('collab_project',$p->id,gd_client_portal_get_dashboard_url())).'">Open workspace</a></td></tr>';}if(!$projects)echo '<tr><td colspan="6">No projects found.</td></tr>';echo '</tbody></table></div>';}
function gd_client_portal_register_collaboration_admin(){add_submenu_page('gd-client-portal','Collaboration','Collaboration','gd_client_portal_access_admin','gd-client-portal-collaboration','gd_client_portal_collaboration_admin');}add_action('admin_menu','gd_client_portal_register_collaboration_admin',20);
function gd_client_portal_register_collaboration_assets(){wp_register_style('gdcp-collaboration-approvals-ux',GD_CLIENT_PORTAL_URL.'assets/collaboration-approvals-ux.css',array('gd-client-portal-collaboration'),GD_CLIENT_PORTAL_VERSION);wp_register_style('gd-client-portal-collaboration',GD_CLIENT_PORTAL_URL.'assets/collaboration.css',array('gd-client-portal'),GD_CLIENT_PORTAL_VERSION);wp_register_script('gd-client-portal-collaboration',GD_CLIENT_PORTAL_URL.'assets/collaboration.js',array(),GD_CLIENT_PORTAL_VERSION,true);}add_action('wp_enqueue_scripts','gd_client_portal_register_collaboration_assets');add_action('admin_enqueue_scripts','gd_client_portal_register_collaboration_assets');
