<?php
/**
 * GD Client Portal v3.4 — Contracts & Digital Agreements.
 * Provides versioned agreements and client acknowledgement/sign-off records.
 */
if (!defined('ABSPATH')) exit;

function gd_client_portal_contracts_table(){ global $wpdb; return $wpdb->prefix.'gd_portal_contracts'; }
function gd_client_portal_contracts_activate_table(){
    global $wpdb; require_once ABSPATH.'wp-admin/includes/upgrade.php'; $c=$wpdb->get_charset_collate(); $t=gd_client_portal_contracts_table();
    dbDelta("CREATE TABLE $t (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,contract_number varchar(60) NOT NULL,tenant_id bigint(20) unsigned NOT NULL DEFAULT 0,user_id bigint(20) unsigned NOT NULL DEFAULT 0,project_id bigint(20) unsigned NOT NULL DEFAULT 0,quote_id bigint(20) unsigned NOT NULL DEFAULT 0,parent_id bigint(20) unsigned NOT NULL DEFAULT 0,version int(10) unsigned NOT NULL DEFAULT 1,title varchar(255) NOT NULL,body longtext NOT NULL,status varchar(30) NOT NULL DEFAULT 'draft',valid_until date NULL,created_by bigint(20) unsigned NOT NULL DEFAULT 0,created_at datetime DEFAULT CURRENT_TIMESTAMP,updated_at datetime DEFAULT CURRENT_TIMESTAMP,submitted_at datetime NULL,accepted_at datetime NULL,declined_at datetime NULL,PRIMARY KEY(id),UNIQUE KEY contract_number(contract_number),KEY tenant_id(tenant_id),KEY user_id(user_id),KEY project_id(project_id),KEY quote_id(quote_id),KEY parent_id(parent_id),KEY status(status)) $c;");
}
function gd_client_portal_contracts_upgrade(){ if(absint(get_option('gd_client_portal_contracts_schema_version',0))<1){ gd_client_portal_contracts_activate_table(); update_option('gd_client_portal_contracts_schema_version',1); } }
// Schema lifecycle is managed centrally by GDCP_Migration_Manager (v6.8+).function gd_client_portal_contracts_statuses(){ return array('draft'=>'Draft','sent'=>'Sent','accepted'=>'Accepted','declined'=>'Declined','expired'=>'Expired','superseded'=>'Superseded'); }
function gd_client_portal_contracts_number(){ return 'GD-CON-'.gmdate('Y').'-'.str_pad((string)wp_rand(1,999999),6,'0',STR_PAD_LEFT); }
function gd_client_portal_contract_access($row,$admin=false){
    if(!$row || !is_user_logged_in() || !gd_client_portal_verify_request()) return false;
    if(gd_client_portal_is_platform_admin()) return true;
    $tenant=absint(gd_client_portal_get_current_tenant_id()); if(!$tenant || absint($row->tenant_id)!==$tenant) return false;
    return $admin ? gd_client_portal_user_is_tenant_admin() : (gd_client_portal_user_is_tenant_admin() || absint($row->user_id)===gd_client_portal_cached_current_user_id());
}
function gd_client_portal_contracts_get($limit=100){ return gdcp_contract_service()->list_visible($limit); }
function gd_client_portal_contract_latest($project_id){ return gdcp_contract_service()->latest_for_project($project_id); }
function gd_client_portal_contract_by_id($id){ return gdcp_contract_service()->find($id); }
function gd_client_portal_contracts_notify($user_id,$title,$body,$project_id=0,$tenant_id=0){ if(function_exists('gd_client_portal_create_notification')) gd_client_portal_create_notification(absint($user_id),$title,$body,'contract',absint($project_id),absint($tenant_id)); }
function gd_client_portal_contracts_audit($event,$summary,$row,$extra=array()){ if(function_exists('gd_client_portal_audit_log')) gd_client_portal_audit_log($event,$summary,absint($row->project_id),absint($row->tenant_id),$row->contract_number,'contract',absint($row->id),$extra); }

// Accepted quotes can be turned into a draft agreement from the admin screen.
function gd_client_portal_contracts_create_from_quote($quote_id){
    $id=gdcp_contract_service()->create_from_quote($quote_id);
    if($id){ $row=gd_client_portal_contract_by_id($id); if($row)gd_client_portal_contracts_audit('contract_created',__('Contract created from accepted quote','gd-client-portal'),$row,array('quote_id'=>absint($quote_id))); }
    return $id;
}
function gd_client_portal_contracts_create_ajax(){
    if(!is_user_logged_in()||!gd_client_portal_verify_request()||!(gd_client_portal_is_platform_admin()||gd_client_portal_user_is_tenant_admin()))wp_send_json_error(array('message'=>'Access denied.'),403); check_ajax_referer('gd_client_portal_contracts_admin','nonce');
    $tenant=absint($_POST['tenant_id']??0); $user=absint($_POST['user_id']??0); $project=absint($_POST['project_id']??0); $title=sanitize_text_field(wp_unslash($_POST['title']??'')); $body=wp_kses_post(wp_unslash($_POST['body']??'')); $valid=sanitize_text_field($_POST['valid_until']??'');
    if(!gd_client_portal_is_platform_admin())$tenant=absint(gd_client_portal_get_current_tenant_id()); if(!$tenant||!$user||!$title||!$body)wp_send_json_error(array('message'=>'Tenant, client, title and agreement text are required.'));
    if(absint(gd_client_portal_get_user_tenant_id($user))!==$tenant)wp_send_json_error(array('message'=>'Client is not assigned to the selected tenant.'),403);
    if($project){$p=gd_client_portal_get_project_by_id($project);if(!$p||absint($p->tenant_id)!==$tenant||absint($p->user_id)!==$user)wp_send_json_error(array('message'=>'Project does not match client/tenant.'),403);}
    $id=gdcp_contract_service()->create_sent(array('tenant_id'=>$tenant,'user_id'=>$user,'project_id'=>$project,'title'=>$title,'body'=>$body,'status'=>'sent','valid_until'=>preg_match('/^\d{4}-\d{2}-\d{2}$/',$valid)?$valid:null,'created_by'=>gd_client_portal_cached_current_user_id()));
    if(!$id)wp_send_json_error(array('message'=>'Could not create contract.')); $row=gd_client_portal_contract_by_id($id); gd_client_portal_contracts_notify($user,__('New agreement','gd-client-portal'),sprintf(__('Agreement %s is ready for your review.', 'gd-client-portal'),$row->contract_number),$project,$tenant); gd_client_portal_contracts_audit('contract_sent',__('Agreement sent to client','gd-client-portal'),$row); wp_send_json_success(array('message'=>'Agreement created and sent.','id'=>$row->id));
}
add_action('wp_ajax_gd_client_portal_contract_create','gd_client_portal_contracts_create_ajax');

function gd_client_portal_contract_decision_ajax(){
    gd_client_portal_ajax_guard('gd_client_portal_contract','nonce'); $id=absint($_POST['contract_id']??0); $decision=sanitize_key($_POST['decision']??''); $typed=sanitize_text_field(wp_unslash($_POST['typed_name']??'')); $agree=!empty($_POST['agree']); $row=gd_client_portal_contract_by_id($id); if(!$row||!gd_client_portal_contract_access($row))wp_send_json_error(array('message'=>'Agreement access denied.'),403);
    $result=gdcp_contract_service()->decide($id,$decision,$typed,$agree); if(is_wp_error($result))wp_send_json_error(array('message'=>$result->get_error_message())); $row=$result;
    gd_client_portal_contracts_audit('contract_'.$decision,$decision==='accepted'?__('Agreement accepted by client','gd-client-portal'):__('Agreement declined by client','gd-client-portal'),$row,array('typed_name'=>$typed,'decision'=>$decision));
    $admins=get_users(array('role'=>'gd_client_portal_tenant_admin','meta_key'=>'gd_client_portal_tenant_id','meta_value'=>$row->tenant_id,'fields'=>'ID')); foreach((array)$admins as $uid)gd_client_portal_contracts_notify($uid,__('Agreement decision','gd-client-portal'),sprintf(__('%s was %s by the client.', 'gd-client-portal'),$row->contract_number,$decision),$row->project_id,$row->tenant_id);
    wp_send_json_success(array('message'=>$decision==='accepted'?'Agreement accepted.':'Agreement declined.'));
}
add_action('wp_ajax_gd_client_portal_contract_decision','gd_client_portal_contract_decision_ajax');

function gd_client_portal_contracts_activate_signature_table(){ global $wpdb; require_once ABSPATH.'wp-admin/includes/upgrade.php'; $c=$wpdb->get_charset_collate(); $t=gd_client_portal_contracts_table().'_signatures'; dbDelta("CREATE TABLE $t (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,contract_id bigint(20) unsigned NOT NULL,tenant_id bigint(20) unsigned NOT NULL DEFAULT 0,user_id bigint(20) unsigned NOT NULL DEFAULT 0,decision varchar(20) NOT NULL,typed_name varchar(255) NULL,ip_hash char(64) NULL,user_agent varchar(500) NULL,created_at datetime DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY contract_id(contract_id),KEY tenant_id(tenant_id),KEY user_id(user_id)) $c;"); }
function gd_client_portal_contracts_signature_upgrade(){if(absint(get_option('gd_client_portal_contracts_signature_schema_version',0))<1){gd_client_portal_contracts_activate_signature_table();update_option('gd_client_portal_contracts_signature_schema_version',1);}}
// Signature schema lifecycle is managed centrally by GDCP_Migration_Manager (v6.8+).

function gd_client_portal_render_contracts(){
    if(!is_user_logged_in()||!gd_client_portal_verify_request())return '<div class="gd-contracts-notice">Please sign in to access agreements.</div>';
    $rows=gd_client_portal_contracts_get(); wp_enqueue_style('gd-client-portal-contracts',GD_CLIENT_PORTAL_URL.'assets/contracts.css',array(),GD_CLIENT_PORTAL_VERSION); wp_enqueue_script('gd-client-portal-contracts',GD_CLIENT_PORTAL_URL.'assets/contracts.js',array(),GD_CLIENT_PORTAL_VERSION,true); wp_localize_script('gd-client-portal-contracts','GDContracts',array('ajax_url'=>admin_url('admin-ajax.php'),'nonce'=>wp_create_nonce('gd_client_portal_contract')));
    ob_start(); ?><div class="gd-contracts"><section class="gd-contracts-hero"><span>Agreements workspace</span><h2>Contracts &amp; Digital Agreements</h2><p>Review project agreements and record your acknowledgement securely.</p></section><div class="gd-contract-list"><?php if(!$rows):?><div class="gd-contract-empty">No agreements are available.</div><?php else: foreach($rows as $r): $status=gd_client_portal_contracts_statuses()[$r->status]??ucfirst($r->status); ?><article class="gd-contract-card"><div class="gd-contract-card-head"><div><small><?php echo esc_html($r->contract_number);?> · v<?php echo intval($r->version);?></small><h3><?php echo esc_html($r->title);?></h3></div><span class="gd-contract-status status-<?php echo esc_attr($r->status);?>"><?php echo esc_html($status);?></span></div><div class="gd-contract-body"><?php echo wpautop(wp_kses_post($r->body));?></div><div class="gd-contract-meta"><span>Issued <?php echo esc_html(wp_date(get_option('date_format'),strtotime($r->created_at)));?></span><?php if($r->valid_until):?><span>Valid until <?php echo esc_html($r->valid_until);?></span><?php endif;?></div><?php if($r->status==='sent' && absint($r->user_id)===gd_client_portal_cached_current_user_id()):?><div class="gd-contract-decision"><label><input type="checkbox" class="gd-contract-agree" data-id="<?php echo intval($r->id);?>"> I confirm that I have reviewed this agreement.</label><input type="text" class="gd-contract-name" data-id="<?php echo intval($r->id);?>" placeholder="Type your full name"><div><button type="button" class="gd-contract-accept" data-id="<?php echo intval($r->id);?>">Accept agreement</button><button type="button" class="gd-contract-decline" data-id="<?php echo intval($r->id);?>">Decline</button></div><span class="gd-contract-result" data-id="<?php echo intval($r->id);?>"></span></div><?php endif;?></article><?php endforeach; endif;?></div></div><?php return ob_get_clean(); }
add_shortcode('gd_contracts','gd_client_portal_render_contracts'); add_shortcode('gd_digital_agreements','gd_client_portal_render_contracts');

function gd_client_portal_contracts_admin_menu(){add_submenu_page('gd-client-portal',__('Contracts & Digital Agreements','gd-client-portal'),__('Contracts & Agreements','gd-client-portal'),'gd_client_portal_access_admin','gd-client-portal-contracts','gd_client_portal_render_contracts_admin');}
add_action('admin_menu','gd_client_portal_contracts_admin_menu',20);
function gd_client_portal_render_contracts_admin(){
    if(!current_user_can('gd_client_portal_access_admin'))wp_die('Access denied.'); $rows=gd_client_portal_contracts_get(250); $users=gd_client_portal_is_platform_admin()?get_users(array('fields'=>array('ID','display_name','user_email'))):get_users(array('role__not_in'=>array('administrator','gd_client_portal_tenant_admin'),'meta_key'=>'gd_client_portal_tenant_id','meta_value'=>gd_client_portal_get_current_tenant_id(),'fields'=>array('ID','display_name','user_email'))); $tenants=gd_client_portal_is_platform_admin()?gd_client_portal_get_all_tenants():array(); wp_enqueue_style('gd-client-portal-contracts-admin',GD_CLIENT_PORTAL_URL.'assets/contracts.css',array(),GD_CLIENT_PORTAL_VERSION); wp_enqueue_script('gd-client-portal-contracts-admin',GD_CLIENT_PORTAL_URL.'assets/contracts.js',array(),GD_CLIENT_PORTAL_VERSION,true); wp_localize_script('gd-client-portal-contracts-admin','GDContractsAdmin',array('ajax_url'=>admin_url('admin-ajax.php'),'nonce'=>wp_create_nonce('gd_client_portal_contracts_admin')));
    ?><div class="wrap gd-contracts-admin"><h1>Contracts &amp; Digital Agreements</h1><p>Create agreements for clients and monitor acknowledgement status.</p><hr><h2>Create Agreement</h2><form id="gd-contract-create"><input type="hidden" name="action" value="gd_client_portal_contract_create"><input type="hidden" name="nonce" value="<?php echo esc_attr(wp_create_nonce('gd_client_portal_contracts_admin'));?>"><?php if(gd_client_portal_is_platform_admin()):?><p><label>Tenant <select name="tenant_id" required><option value="">Select tenant</option><?php foreach((array)$tenants as $tid=>$t):?><option value="<?php echo intval($tid);?>"><?php echo esc_html($t['name']??('Tenant #'.$tid));?></option><?php endforeach;?></select></label></p><?php else:?><input type="hidden" name="tenant_id" value="<?php echo intval(gd_client_portal_get_current_tenant_id());?>"><?php endif;?><table class="form-table"><tr><th>Client</th><td><select name="user_id" required><option value="">Select client</option><?php foreach((array)$users as $u):?><option value="<?php echo intval($u->ID);?>"><?php echo esc_html($u->display_name.' — '.$u->user_email);?></option><?php endforeach;?></select></td></tr><tr><th>Project ID</th><td><input type="number" name="project_id" min="0" value="0"></td></tr><tr><th>Title</th><td><input class="regular-text" name="title" required></td></tr><tr><th>Agreement text</th><td><textarea class="large-text" rows="10" name="body" required></textarea></td></tr><tr><th>Valid until</th><td><input type="date" name="valid_until"></td></tr></table><p><button class="button button-primary" type="submit">Create &amp; Send Agreement</button> <span id="gd-contract-create-result"></span></p></form><hr><h2>Agreement Register</h2><table class="widefat striped"><thead><tr><th>Contract</th><th>Client</th><th>Project</th><th>Version</th><th>Status</th><th>Issued</th></tr></thead><tbody><?php foreach($rows as $r):$u=gd_client_portal_cached_user($r->user_id);?><tr><td><strong><?php echo esc_html($r->contract_number);?></strong><br><?php echo esc_html($r->title);?></td><td><?php echo esc_html($u?$u->display_name:'—');?></td><td><?php echo $r->project_id?'#'.intval($r->project_id):'—';?></td><td>v<?php echo intval($r->version);?></td><td><?php echo esc_html(gd_client_portal_contracts_statuses()[$r->status]??$r->status);?></td><td><?php echo esc_html(wp_date(get_option('date_format'),strtotime($r->created_at)));?></td></tr><?php endforeach;?></tbody></table></div><?php
}

function gd_client_portal_contracts_on_quote_accepted($quote){
    if(!$quote || !is_object($quote)) return; $id=gd_client_portal_contracts_create_from_quote(absint($quote->id));
    if($id){ $row=gd_client_portal_contract_by_id($id); if($row && $row->status==='draft' && gdcp_contract_service()->send($id)){ $row=gd_client_portal_contract_by_id($id); gd_client_portal_contracts_notify($row->user_id,__('New agreement','gd-client-portal'),sprintf(__('Agreement %s is ready for your review.', 'gd-client-portal'),$row->contract_number),$row->project_id,$row->tenant_id); gd_client_portal_contracts_audit('contract_sent',__('Agreement automatically sent after quote acceptance','gd-client-portal'),$row,array('quote_id'=>$quote->id)); } }
}
add_action('gd_client_portal_quote_accepted','gd_client_portal_contracts_on_quote_accepted',20,1);
