<?php
if (!defined('ABSPATH')) exit;
class GDCP_Document_Service {
 public function get($id){return gdcp_document_repository()->find($id);}
 public function upload(array $data){$tenant=absint($data['tenant_id']??0);$user=absint($data['user_id']??0);$project=absint($data['project_id']??0);$file=sanitize_file_name($data['file_name']??'');if(!$file)return new WP_Error('invalid_document','Invalid document.');$existing=gdcp_document_repository()->find_active_version($tenant,$user,$project,(string)($data['folder']??''),$file,true);$version=$existing?absint($existing->version)+1:1;if($existing&&!gdcp_document_repository()->update($existing->id,array('status'=>'superseded','updated_at'=>current_time('mysql'))))return new WP_Error('document_update_failed','Could not supersede the previous document.');$data['file_name']=$file;$data['version']=$version;$data['parent_id']=$existing?absint($existing->id):0;$id=gdcp_document_repository()->insert($data);if(!$id)return new WP_Error('document_insert_failed','Could not save the document record.');return gdcp_document_repository()->find($id);}
 public function change_status($id,$status){$status=sanitize_key($status);if(!in_array($status,array('active','archived','approved','rejected','superseded'),true))return new WP_Error('invalid_status','Invalid status.');if(!gdcp_document_repository()->update($id,array('status'=>$status,'updated_at'=>current_time('mysql'))))return new WP_Error('document_update_failed','Could not update the document.');return gdcp_document_repository()->find($id);}
 public function delete($id){$row=gdcp_document_repository()->find($id,true);if(!$row)return new WP_Error('not_found','Document not found.');if(!gdcp_document_repository()->delete($id))return new WP_Error('delete_failed','Could not delete the document.');return $row;}
 public function create_request(array $data){$id=gdcp_document_repository()->insert_request($data);return $id?gdcp_document_repository()->find_request($id):new WP_Error('request_insert_failed','Could not create the document request.');}
 public function fulfill_request($id,$document_id){$r=gdcp_document_repository()->find_request($id,true);if(!$r)return new WP_Error('not_found','Request not found.');if(!gdcp_document_repository()->update_request($id,array('status'=>'fulfilled','fulfilled_document_id'=>absint($document_id),'updated_at'=>current_time('mysql'))))return new WP_Error('request_update_failed','Could not close the request.');return gdcp_document_repository()->find_request($id);}
}
function gdcp_document_service(){static $s;return $s?:($s=new GDCP_Document_Service());}
