<?php
if (!defined('ABSPATH')) exit;

class GDCP_Document_Repository {
    public function documents_table(){ return gd_client_portal_documents_table(); }
    public function requests_table(){ return gd_client_portal_document_requests_table(); }
    public function find($id,$lock=false){ global $wpdb; $sql='SELECT * FROM '.$this->documents_table().' WHERE id=%d LIMIT 1'.($lock?' FOR UPDATE':''); return $wpdb->get_row($wpdb->prepare($sql,absint($id))); }
    public function find_active_version($tenant,$user,$project,$folder,$file_name,$lock=false){ global $wpdb; $sql="SELECT * FROM ".$this->documents_table()." WHERE tenant_id=%d AND user_id=%d AND project_id=%d AND folder=%s AND file_name=%s AND status='active' ORDER BY version DESC LIMIT 1".($lock?' FOR UPDATE':''); return $wpdb->get_row($wpdb->prepare($sql,absint($tenant),absint($user),absint($project),$folder,$file_name)); }
    public function insert(array $data){ global $wpdb; $fields=array('tenant_id'=>'%d','user_id'=>'%d','project_id'=>'%d','contract_id'=>'%d','parent_id'=>'%d','folder'=>'%s','title'=>'%s','file_name'=>'%s','file_path'=>'%s','file_url'=>'%s','mime_type'=>'%s','filesize'=>'%d','version'=>'%d','status'=>'%s','expires_at'=>'%s','uploaded_by'=>'%d','created_at'=>'%s','updated_at'=>'%s'); $row=array();$fmt=array(); foreach($fields as $k=>$f){if(array_key_exists($k,$data)){$row[$k]=$data[$k];$fmt[]=$f;}} if(!$row||false===$wpdb->insert($this->documents_table(),$row,$fmt)) return false; return absint($wpdb->insert_id); }
    public function update($id,array $data){ global $wpdb; $allowed=array('status'=>'%s','updated_at'=>'%s');$row=array();$fmt=array();foreach($allowed as $k=>$f){if(array_key_exists($k,$data)){$row[$k]=$data[$k];$fmt[]=$f;}} if(!$row)return false; return false!==$wpdb->update($this->documents_table(),$row,array('id'=>absint($id)),$fmt,array('%d')); }
    public function delete($id){ global $wpdb; return false!==$wpdb->delete($this->documents_table(),array('id'=>absint($id)),array('%d')); }
    public function list(array $args=array()){ global $wpdb; $where=array('1=1');$vals=array(); if(!gd_client_portal_is_platform_admin()){ $tenant=absint(gd_client_portal_get_current_tenant_id());if(!$tenant)return array();$where[]='tenant_id=%d';$vals[]=$tenant;if(!gd_client_portal_user_is_tenant_admin()){$where[]='user_id=%d';$vals[]=gd_client_portal_cached_current_user_id();} } if(!empty($args['project_id'])){$where[]='project_id=%d';$vals[]=absint($args['project_id']);} if(isset($args['status'])&&$args['status']!==''){$where[]='status=%s';$vals[]=sanitize_key($args['status']);}$limit=max(1,min(500,absint($args['limit']??200)));$sql='SELECT * FROM '.$this->documents_table().' WHERE '.implode(' AND ',$where).' ORDER BY folder ASC,parent_id ASC,id DESC LIMIT '.$limit;return $vals?$wpdb->get_results($wpdb->prepare($sql,$vals)):$wpdb->get_results($sql); }
    public function list_requests(array $args=array()){ global $wpdb; $where=array('1=1');$vals=array(); if(isset($args['project_id'])){$where[]='project_id=%d';$vals[]=absint($args['project_id']);} if(isset($args['user_id'])){$where[]='user_id=%d';$vals[]=absint($args['user_id']);} if(isset($args['status'])&&$args['status']!==''){$where[]='status=%s';$vals[]=sanitize_key($args['status']);} $sql='SELECT * FROM '.$this->requests_table().' WHERE '.implode(' AND ',$where).' ORDER BY id DESC'; return $vals?$wpdb->get_results($wpdb->prepare($sql,$vals)):$wpdb->get_results($sql); }
    public function find_request($id,$lock=false){ global $wpdb;$sql='SELECT * FROM '.$this->requests_table().' WHERE id=%d LIMIT 1'.($lock?' FOR UPDATE':'');return $wpdb->get_row($wpdb->prepare($sql,absint($id))); }
    public function insert_request(array $data){ global $wpdb;$fields=array('tenant_id'=>'%d','user_id'=>'%d','project_id'=>'%d','title'=>'%s','description'=>'%s','folder'=>'%s','status'=>'%s','due_date'=>'%s','created_by'=>'%d','fulfilled_document_id'=>'%d','created_at'=>'%s','updated_at'=>'%s');$row=array();$fmt=array();foreach($fields as $k=>$f){if(array_key_exists($k,$data)){$row[$k]=$data[$k];$fmt[]=$f;}}if(!$row||false===$wpdb->insert($this->requests_table(),$row,$fmt))return false;return absint($wpdb->insert_id);}
    public function update_request($id,array $data){global $wpdb;$allowed=array('status'=>'%s','fulfilled_document_id'=>'%d','updated_at'=>'%s');$row=array();$fmt=array();foreach($allowed as $k=>$f){if(array_key_exists($k,$data)){$row[$k]=$data[$k];$fmt[]=$f;}}if(!$row)return false;return false!==$wpdb->update($this->requests_table(),$row,array('id'=>absint($id)),$fmt,array('%d'));}
}
function gdcp_document_repository(){static $r;return $r?:($r=new GDCP_Document_Repository());}
