<?php
/** GD Client Portal v3.5 — Client Files & Document Management 2.0. */
if (!defined('ABSPATH')) exit;

function gd_client_portal_documents_table(){ global $wpdb; return $wpdb->prefix.'gd_portal_documents'; }
function gd_client_portal_document_requests_table(){ global $wpdb; return $wpdb->prefix.'gd_portal_document_requests'; }
function gd_client_portal_documents_activate_tables(){
    global $wpdb; require_once ABSPATH.'wp-admin/includes/upgrade.php'; $c=$wpdb->get_charset_collate();
    $t=gd_client_portal_documents_table();
    dbDelta("CREATE TABLE $t (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,tenant_id bigint(20) unsigned NOT NULL DEFAULT 0,user_id bigint(20) unsigned NOT NULL DEFAULT 0,project_id bigint(20) unsigned NOT NULL DEFAULT 0,contract_id bigint(20) unsigned NOT NULL DEFAULT 0,parent_id bigint(20) unsigned NOT NULL DEFAULT 0,folder varchar(190) NOT NULL DEFAULT '',title varchar(255) NOT NULL,file_name varchar(255) NOT NULL,file_path text NOT NULL,file_url text NULL,mime_type varchar(120) NOT NULL,filesize bigint(20) unsigned NOT NULL DEFAULT 0,version int(10) unsigned NOT NULL DEFAULT 1,status varchar(30) NOT NULL DEFAULT 'active',expires_at date NULL,uploaded_by bigint(20) unsigned NOT NULL DEFAULT 0,created_at datetime DEFAULT CURRENT_TIMESTAMP,updated_at datetime DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY tenant_id(tenant_id),KEY user_id(user_id),KEY project_id(project_id),KEY contract_id(contract_id),KEY parent_id(parent_id),KEY status(status),KEY folder(folder)) $c;");
    $r=gd_client_portal_document_requests_table();
    dbDelta("CREATE TABLE $r (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,tenant_id bigint(20) unsigned NOT NULL DEFAULT 0,user_id bigint(20) unsigned NOT NULL DEFAULT 0,project_id bigint(20) unsigned NOT NULL DEFAULT 0,title varchar(255) NOT NULL,description text NULL,folder varchar(190) NOT NULL DEFAULT '',status varchar(30) NOT NULL DEFAULT 'open',due_date date NULL,created_by bigint(20) unsigned NOT NULL DEFAULT 0,fulfilled_document_id bigint(20) unsigned NOT NULL DEFAULT 0,created_at datetime DEFAULT CURRENT_TIMESTAMP,updated_at datetime DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY tenant_id(tenant_id),KEY user_id(user_id),KEY project_id(project_id),KEY status(status)) $c;");
}
function gd_client_portal_documents_upgrade(){ if(absint(get_option('gd_client_portal_documents_schema_version',0))<1){gd_client_portal_documents_activate_tables();update_option('gd_client_portal_documents_schema_version',1);} }
// Schema lifecycle is managed centrally by GDCP_Migration_Manager (v6.8+).

function gd_client_portal_document_allowed_mimes(){return array('pdf'=>'application/pdf','doc'=>'application/msword','docx'=>'application/vnd.openxmlformats-officedocument.wordprocessingml.document','xls'=>'application/vnd.ms-excel','xlsx'=>'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','ppt'=>'application/vnd.ms-powerpoint','pptx'=>'application/vnd.openxmlformats-officedocument.presentationml.presentation','txt'=>'text/plain','csv'=>'text/csv','jpg'=>'image/jpeg','jpeg'=>'image/jpeg','png'=>'image/png','webp'=>'image/webp','zip'=>'application/zip');}
function gd_client_portal_document_access($row,$write=false){
    if(!$row || !is_user_logged_in() || !gd_client_portal_verify_request()) return false;
    if(gd_client_portal_is_platform_admin()) return true;
    $tenant=absint(gd_client_portal_get_current_tenant_id()); if(!$tenant || absint($row->tenant_id)!==$tenant)return false;
    if(gd_client_portal_user_is_tenant_admin()) return true;
    if(absint($row->user_id)===gd_client_portal_cached_current_user_id())return true;
    if(absint($row->project_id)){ $p=gd_client_portal_get_project_by_id($row->project_id); if($p && gd_client_portal_verify_project_access($p))return true; }
    return false;
}
function gd_client_portal_documents_get($args=array()){ return gdcp_document_repository()->list($args); }
function gd_client_portal_document_by_id($id){ return gdcp_document_repository()->find($id); }
function gd_client_portal_document_notify($user,$title,$body,$project=0,$tenant=0){if(function_exists('gd_client_portal_create_notification')&&$user)gd_client_portal_create_notification(absint($user),$title,$body,'document',absint($project),absint($tenant));}
function gd_client_portal_document_audit($event,$summary,$row,$extra=array()){if(function_exists('gd_client_portal_audit_log'))gd_client_portal_audit_log($event,$summary,absint($row->project_id),absint($row->tenant_id),$row->file_name,'document',absint($row->id),$extra);}

function gd_client_portal_document_upload_ajax(){
    gd_client_portal_ajax_guard('gd_client_portal_documents','nonce'); global $wpdb;
    $project_id=absint($_POST['project_id']??0);$contract_id=absint($_POST['contract_id']??0);$folder=sanitize_text_field(wp_unslash($_POST['folder']??''));$title=sanitize_text_field(wp_unslash($_POST['title']??''));$expires=sanitize_text_field(wp_unslash($_POST['expires_at']??''));$user_id=gd_client_portal_cached_current_user_id();
    $project=$project_id?gd_client_portal_get_project_by_id($project_id):false;
    if($project && !gd_client_portal_verify_project_access($project,true))wp_send_json_error(array('message'=>'Project access denied.'),403);
    if($contract_id){$contract=function_exists('gd_client_portal_contract_by_id')?gd_client_portal_contract_by_id($contract_id):false;if(!$contract)wp_send_json_error(array('message'=>'Contract not found.'),404);if($project_id && (absint($contract->project_id)!==$project_id || absint($contract->tenant_id)!==absint($project->tenant_id) || absint($contract->user_id)!==absint($project->user_id)))wp_send_json_error(array('message'=>'Contract does not match project/client.'),403);if(!$project_id && !gd_client_portal_is_platform_admin() && !gd_client_portal_user_is_tenant_admin() && absint($contract->tenant_id)!==absint(gd_client_portal_get_current_tenant_id()))wp_send_json_error(array('message'=>'Contract access denied.'),403);}
    if(!$project && !gd_client_portal_is_platform_admin() && !gd_client_portal_user_is_tenant_admin())$project_id=0;
    if(!empty($_FILES['document_file']['error']))wp_send_json_error(array('message'=>'Please select a valid file.'));
    $file=$_FILES['document_file'];$allowed=gd_client_portal_document_allowed_mimes();$max_size=apply_filters('gd_client_portal_document_max_upload_size',10*MB_IN_BYTES);if(absint($file['size'])<=0||absint($file['size'])>$max_size)wp_send_json_error(array('message'=>'The selected file exceeds the allowed upload size.'));$ext=strtolower(pathinfo($file['name'],PATHINFO_EXTENSION));if(!isset($allowed[$ext]))wp_send_json_error(array('message'=>'This file type is not allowed.'));$checked=wp_check_filetype_and_ext($file['tmp_name'],$file['name'],$allowed);if(empty($checked['ext'])||empty($checked['type'])||$checked['ext']!==$ext)wp_send_json_error(array('message'=>'The uploaded file failed type validation.'));
    require_once ABSPATH.'wp-admin/includes/file.php'; $upload=wp_handle_upload($file,array('test_form'=>false,'mimes'=>$allowed));if(!empty($upload['error']))wp_send_json_error(array('message'=>$upload['error']));
    $tenant=$project?absint($project->tenant_id):absint(gd_client_portal_get_current_tenant_id()); if(!$tenant && gd_client_portal_is_platform_admin())$tenant=0;
    $owner=$project?absint($project->user_id):$user_id;$row=gdcp_document_service()->upload(array('tenant_id'=>$tenant,'user_id'=>$owner,'project_id'=>$project_id,'contract_id'=>$contract_id,'folder'=>$folder,'title'=>$title?:sanitize_text_field(pathinfo($file['name'],PATHINFO_FILENAME)),'file_name'=>$file['name'],'file_path'=>$upload['file'],'file_url'=>$upload['url'],'mime_type'=>$upload['type'],'filesize'=>absint($file['size']),'status'=>'active','expires_at'=>preg_match('/^\d{4}-\d{2}-\d{2}$/',$expires)?$expires:null,'uploaded_by'=>$user_id,'created_at'=>current_time('mysql'),'updated_at'=>current_time('mysql')));
    if(is_wp_error($row))wp_send_json_error(array('message'=>$row->get_error_message()));$version=absint($row->version);gd_client_portal_document_audit('document_uploaded',sprintf(__('Document uploaded: %s','gd-client-portal'),$row->file_name),$row,array('version'=>$version,'folder'=>$folder));if($owner!==$user_id)gd_client_portal_document_notify($owner,__('New document uploaded','gd-client-portal'),sprintf(__('A new document is available: %s','gd-client-portal'),$row->title),$project_id,$tenant);wp_send_json_success(array('message'=>sprintf(__('Document uploaded (v%d).','gd-client-portal'),$version),'document_id'=>$row->id));
}
add_action('wp_ajax_gd_client_portal_document_upload','gd_client_portal_document_upload_ajax');

function gd_client_portal_document_status_ajax(){
    gd_client_portal_ajax_guard('gd_client_portal_documents','nonce');$id=absint($_POST['document_id']??0);$row=gd_client_portal_document_by_id($id);if(!$row||!gd_client_portal_document_access($row,true))wp_send_json_error(array('message'=>'Access denied.'),403);$status=sanitize_key($_POST['status']??'active');$row=gdcp_document_service()->change_status($id,$status);if(is_wp_error($row))wp_send_json_error(array('message'=>$row->get_error_message()),400);gd_client_portal_document_audit('document_status_changed',sprintf(__('Document status changed: %s','gd-client-portal'),$status),$row,array('status'=>$status));wp_send_json_success(array('message'=>__('Document updated.','gd-client-portal')));
}
add_action('wp_ajax_gd_client_portal_document_status','gd_client_portal_document_status_ajax');

function gd_client_portal_document_delete_ajax(){
    gd_client_portal_ajax_guard('gd_client_portal_documents','nonce');$row=gd_client_portal_document_by_id(absint($_POST['document_id']??0));if(!$row||!gd_client_portal_document_access($row,true))wp_send_json_error(array('message'=>'Access denied.'),403);if($row->file_path&&file_exists($row->file_path))@unlink($row->file_path);$deleted=gdcp_document_service()->delete($row->id);if(is_wp_error($deleted))wp_send_json_error(array('message'=>$deleted->get_error_message()),400);gd_client_portal_document_audit('document_deleted',sprintf(__('Document deleted: %s','gd-client-portal'),$row->file_name),$row);wp_send_json_success(array('message'=>__('Document deleted.','gd-client-portal')));
}
add_action('wp_ajax_gd_client_portal_document_delete','gd_client_portal_document_delete_ajax');

function gd_client_portal_document_download(){ $id=absint($_GET['document_id']??0); $nonce=isset($_GET['_wpnonce'])?sanitize_text_field(wp_unslash($_GET['_wpnonce'])):''; if(!$id || !wp_verify_nonce($nonce,'gd_client_portal_document_download_'.$id)) wp_die(esc_html__('Invalid download request.','gd-client-portal'),'',array('response'=>403)); if(!is_user_logged_in())wp_die(esc_html__('Please sign in.','gd-client-portal'),'',array('response'=>403));$row=gd_client_portal_document_by_id($id);if(!$row||!gd_client_portal_document_access($row))wp_die(esc_html__('You do not have access to this document.','gd-client-portal'),'',array('response'=>403));if($row->status==='archived'||$row->status==='rejected')wp_die(esc_html__('This document is no longer available.','gd-client-portal'),'',array('response'=>410));if($row->expires_at&&strtotime($row->expires_at.' 23:59:59')<current_time('timestamp'))wp_die(esc_html__('This document has expired.','gd-client-portal'),'',array('response'=>410));if(!gd_client_portal_verify_upload_path($row->file_path))wp_die(esc_html__('File unavailable.','gd-client-portal'),'',array('response'=>404));$safe_path=realpath($row->file_path);nocache_headers();header('X-Content-Type-Options: nosniff');header('Content-Type: '.($row->mime_type?:'application/octet-stream'));header('Content-Length: '.filesize($safe_path));header('Content-Disposition: attachment; filename="'.sanitize_file_name($row->file_name).'"');readfile($safe_path);exit;}
add_action('admin_post_gd_client_portal_document_download','gd_client_portal_document_download');

function gd_client_portal_document_requests_ajax(){
    gd_client_portal_ajax_guard('gd_client_portal_documents','nonce');$action=sanitize_key($_POST['request_action']??'create');$id=absint($_POST['request_id']??0);
    if($action==='create'){$project_id=absint($_POST['project_id']??0);$p=$project_id?gd_client_portal_get_project_by_id($project_id):false;if(!$p||!gd_client_portal_verify_project_access($p,true))wp_send_json_error(array('message'=>'Project access denied.'),403);if(!(gd_client_portal_is_platform_admin()||gd_client_portal_user_is_tenant_admin()))wp_send_json_error(array('message'=>'Admin access required.'));$title=sanitize_text_field(wp_unslash($_POST['title']??''));if(!$title)wp_send_json_error(array('message'=>'Request title is required.'));$r=gdcp_document_service()->create_request(array('tenant_id'=>absint($p->tenant_id),'user_id'=>absint($p->user_id),'project_id'=>$project_id,'title'=>$title,'description'=>sanitize_textarea_field(wp_unslash($_POST['description']??'')),'folder'=>sanitize_text_field(wp_unslash($_POST['folder']??'')),'status'=>'open','due_date'=>sanitize_text_field($_POST['due_date']??'')?:null,'created_by'=>gd_client_portal_cached_current_user_id(),'created_at'=>current_time('mysql'),'updated_at'=>current_time('mysql')));if(is_wp_error($r))wp_send_json_error(array('message'=>$r->get_error_message()),400);gd_client_portal_document_notify($p->user_id,__('Document requested','gd-client-portal'),sprintf(__('Please provide: %s','gd-client-portal'),$title),$project_id,$p->tenant_id);wp_send_json_success(array('message'=>__('Document request sent.','gd-client-portal')));}
    if($action==='close'){$r=gdcp_document_repository()->find_request($id);if(!$r||!(gd_client_portal_is_platform_admin()||gd_client_portal_user_is_tenant_admin())||!gd_client_portal_verify_tenant_access($r->tenant_id))wp_send_json_error(array('message'=>'Access denied.'),403);$result=gdcp_document_service()->fulfill_request($id,0);if(is_wp_error($result))wp_send_json_error(array('message'=>$result->get_error_message()),400);wp_send_json_success(array('message'=>__('Request closed.','gd-client-portal')));}
    wp_send_json_error(array('message'=>'Invalid request.'));
}
add_action('wp_ajax_gd_client_portal_document_request','gd_client_portal_document_requests_ajax');

function gd_client_portal_render_documents($atts=array()){
    if(!is_user_logged_in()||!gd_client_portal_verify_request())return gd_client_portal_render_access_gate(__('Document Center','gd-client-portal'),__('Please sign in to access your files.','gd-client-portal'));
    $atts=shortcode_atts(array('project_id'=>0),$atts);$project_id=absint($atts['project_id']?:($_GET['project_id']??0));if($project_id){$p=gd_client_portal_get_project_by_id($project_id);if(!$p||!gd_client_portal_verify_project_access($p))return gd_client_portal_render_access_gate(__('Document Center','gd-client-portal'),__('You do not have access to this project.','gd-client-portal'));}
    $docs=gd_client_portal_documents_get(array('project_id'=>$project_id,'limit'=>300));$nonce=wp_create_nonce('gd_client_portal_documents');ob_start();wp_enqueue_style('gd-client-portal-documents');wp_enqueue_script('gd-client-portal-documents');
    echo '<div class="gd-doc-center"><header class="gd-doc-hero"><div><span>GD CLIENT PORTAL · V3.5</span><h2>'.esc_html__('Client Files & Documents','gd-client-portal').'</h2><p>'.esc_html__('Organize project files, versions, approvals and document requests in one secure workspace.','gd-client-portal').'</p></div><strong>'.count($docs).' '.esc_html__('documents','gd-client-portal').'</strong></header>';
    echo '<form class="gd-doc-upload" enctype="multipart/form-data"><input type="hidden" name="project_id" value="'.intval($project_id).'"/><input type="hidden" name="nonce" value="'.esc_attr($nonce).'"/><input name="title" placeholder="'.esc_attr__('Document title','gd-client-portal').'"/><input name="folder" placeholder="'.esc_attr__('Folder (e.g. Briefs / Brand)','gd-client-portal').'"/><input name="expires_at" type="date" title="'.esc_attr__('Expiry date','gd-client-portal').'"/><input type="file" name="document_file" required/><button type="submit">'.esc_html__('Upload document','gd-client-portal').'</button><span class="gd-doc-status" aria-live="polite"></span></form>';
    $folders=array();foreach($docs as $d)$folders[$d->folder][]=$d; if(!$docs)echo '<div class="gd-doc-empty"><strong>'.esc_html__('No documents yet.','gd-client-portal').'</strong><p>'.esc_html__('Uploaded files and requested documents will appear here.','gd-client-portal').'</p></div>';
    foreach($folders as $folder=>$items){echo '<section class="gd-doc-folder"><div class="gd-doc-folder-head"><h3>📁 '.esc_html($folder?:__('General','gd-client-portal')).'</h3><span>'.count($items).'</span></div><div class="gd-doc-grid">';foreach($items as $d){$download=wp_nonce_url(admin_url('admin-post.php?action=gd_client_portal_document_download&document_id='.absint($d->id)),'gd_client_portal_document_download_'.$d->id);$expired=$d->expires_at&&strtotime($d->expires_at.' 23:59:59')<current_time('timestamp');echo '<article class="gd-doc-card '.($expired?'is-expired':'').'"><div class="gd-doc-icon">'.esc_html(strtoupper(pathinfo($d->file_name,PATHINFO_EXTENSION))).'</div><div class="gd-doc-main"><h4>'.esc_html($d->title).'</h4><p>'.esc_html($d->file_name).' · v'.intval($d->version).' · '.size_format($d->filesize).'</p><div class="gd-doc-meta"><span>'.esc_html(ucfirst($d->status)).'</span>'.($d->expires_at?'<span>'.esc_html__('Expires','gd-client-portal').' '.esc_html($d->expires_at).'</span>':'').'</div></div><a class="gd-doc-button" href="'.esc_url($download).'">'.esc_html__('Download','gd-client-portal').'</a></article>'; }echo '</div></section>';}
    $reqs=array(); if($project_id){$reqs=gdcp_document_repository()->list_requests(array('project_id'=>$project_id,'user_id'=>gd_client_portal_cached_current_user_id(),'status'=>'open'));} if($reqs){echo '<section class=\"gd-doc-requests\"><h3>'.esc_html__('Documents requested from you','gd-client-portal').'</h3>';foreach($reqs as $r)echo '<div class=\"gd-doc-request\"><strong>'.esc_html($r->title).'</strong><span>'.esc_html($r->description).'</span>'.($r->due_date?'<small>'.esc_html__('Due','gd-client-portal').' '.esc_html($r->due_date).'</small>':'').'</div>';echo '</section>';} echo '</div>';return ob_get_clean();
}
add_shortcode('gd_documents','gd_client_portal_render_documents');add_shortcode('gd_file_center','gd_client_portal_render_documents');add_shortcode('gd_client_files','gd_client_portal_render_documents');
function gd_client_portal_documents_dashboard(){return gd_client_portal_render_documents(array());} add_action('init',function(){if(function_exists('gd_client_portal_register_dashboard_view'))gd_client_portal_register_dashboard_view('files','gd_client_portal_documents_dashboard');});
function gd_client_portal_documents_admin_menu(){add_submenu_page('gd-client-portal',__('Client Files & Documents','gd-client-portal'),__('Files & Documents','gd-client-portal'),'gd_client_portal_access_admin','gd-client-portal-documents','gd_client_portal_documents_admin_page');} add_action('admin_menu','gd_client_portal_documents_admin_menu',20);
function gd_client_portal_documents_admin_page(){if(!gd_client_portal_user_can_access_admin())wp_die(esc_html__('You do not have permission to access this page.','gd-client-portal'));$docs=gd_client_portal_documents_get(array('limit'=>500));echo '<div class="wrap gd-doc-admin"><h1>'.esc_html__('Client Files & Documents','gd-client-portal').'</h1><p>'.esc_html__('Manage document versions, statuses and tenant-scoped files.','gd-client-portal').'</p><table class="widefat striped"><thead><tr><th>ID</th><th>Document</th><th>Project</th><th>Tenant</th><th>Version</th><th>Status</th><th>Expiry</th><th>Uploaded</th></tr></thead><tbody>';if(!$docs)echo '<tr><td colspan="8">'.esc_html__('No documents found.','gd-client-portal').'</td></tr>';foreach($docs as $d){$p=$d->project_id?gd_client_portal_get_project_by_id($d->project_id):false;$u=gd_client_portal_cached_user($d->uploaded_by);echo '<tr><td>'.intval($d->id).'</td><td><strong>'.esc_html($d->title).'</strong><br><small>'.esc_html($d->file_name).'</small></td><td>'.($p?'#'.intval($p->id).' '.esc_html($p->title):'—').'</td><td>'.intval($d->tenant_id).'</td><td>v'.intval($d->version).'</td><td>'.esc_html(ucfirst($d->status)).'</td><td>'.esc_html($d->expires_at?:'—').'</td><td>'.esc_html($u?$u->display_name:'—').'</td></tr>';}echo '</tbody></table></div>';}
function gd_client_portal_documents_assets(){wp_register_style('gd-client-portal-documents',GD_CLIENT_PORTAL_URL.'assets/documents.css',array('gd-client-portal'),GD_CLIENT_PORTAL_VERSION);wp_register_script('gd-client-portal-documents',GD_CLIENT_PORTAL_URL.'assets/documents.js',array('jquery'),GD_CLIENT_PORTAL_VERSION,true);wp_localize_script('gd-client-portal-documents','GDCPDocuments',array('ajax_url'=>admin_url('admin-ajax.php'),'nonce'=>wp_create_nonce('gd_client_portal_documents'),'action'=>'gd_client_portal_document_upload'));}add_action('wp_enqueue_scripts','gd_client_portal_documents_assets');add_action('admin_enqueue_scripts','gd_client_portal_documents_assets');
