<?php
if(!defined('ABSPATH')) exit;
final class GDCP_Executive_Analytics_Repository {
    private function scope_sql($column='tenant_id',$scope=array(),$prefix=''){ $where='';$args=array();if(empty($scope['global'])){$where=' WHERE '.($prefix?$prefix.'.':'').$column.'=%d';$args[]=absint($scope['tenant_id']??0);}return array($where,$args); }
    public function financial_metrics($scope){ global $wpdb;$t=function_exists('gd_client_portal_billing_invoices_table')?gd_client_portal_billing_invoices_table():'';if(!$t)return array();list($where,$args)=$this->scope_sql('tenant_id',$scope);$sql="SELECT COUNT(*) c,COALESCE(SUM(total),0) revenue,COALESCE(SUM(amount_paid),0) paid,COALESCE(SUM(GREATEST(total-amount_paid,0)),0) outstanding FROM $t$where";$row=$args?$wpdb->get_row($wpdb->prepare($sql,$args)):$wpdb->get_row($sql);return $row?array('invoices'=>(int)$row->c,'revenue'=>(float)$row->revenue,'paid'=>(float)$row->paid,'outstanding'=>(float)$row->outstanding):array(); }
    public function support_metrics($scope){ global $wpdb;$t=function_exists('gd_client_portal_support_table')?gd_client_portal_support_table('tickets'):'';if(!$t)return array();$where=" WHERE status NOT IN ('resolved','closed')";$args=array(current_time('mysql'));if(empty($scope['global'])){$where.=' AND tenant_id=%d';$args[]=absint($scope['tenant_id']??0);}$row=$wpdb->get_row($wpdb->prepare("SELECT COUNT(*) c,SUM(CASE WHEN due_at IS NOT NULL AND due_at < %s THEN 1 ELSE 0 END) overdue FROM $t$where",$args));return $row?array('open_tickets'=>(int)$row->c,'overdue_tickets'=>(int)$row->overdue):array(); }
    public function feedback_metrics($scope){ global $wpdb;$t=function_exists('gd_client_portal_feedback_table')?gd_client_portal_feedback_table('reviews'):'';if(!$t)return array();$where=" WHERE status='published'";$args=array();if(empty($scope['global'])){$where.=' AND tenant_id=%d';$args[]=absint($scope['tenant_id']??0);}$sql="SELECT COUNT(*) c,COALESCE(AVG(rating),0) avg,COALESCE(AVG(recommend)*100,0) rec FROM $t$where";$row=$args?$wpdb->get_row($wpdb->prepare($sql,$args)):$wpdb->get_row($sql);return $row?array('reviews'=>(int)$row->c,'avg_rating'=>round((float)$row->avg,2),'recommend'=>round((float)$row->rec,1)):array(); }
    public function count_by_status($kind,$status,$scope){ global $wpdb;$map=array('contracts'=>array('fn'=>'gd_client_portal_contract_table','arg'=>'agreements'),'documents'=>array('fn'=>'gd_client_portal_documents_table','arg'=>'documents'),'tasks'=>array('fn'=>'gd_client_portal_collab_table','arg'=>'tasks'));if(!isset($map[$kind]))return 0;$fn=$map[$kind]['fn'];$t=function_exists($fn)?call_user_func($fn,$map[$kind]['arg']):'';if(!$t)return 0;list($where,$args)=$this->scope_sql('tenant_id',$scope);if($status!==null)$where.=($where?' AND':' WHERE').' status=%s';if($status!==null)$args[]=$status;$sql="SELECT COUNT(*) FROM $t$where";return $args?(int)$wpdb->get_var($wpdb->prepare($sql,$args)):(int)$wpdb->get_var($sql); }
    public function open_tasks($scope){return $this->count_by_statuses('tasks',array('done','completed'),$scope);}
    private function count_by_statuses($kind,$statuses,$scope){ global $wpdb;$map=array('tasks'=>array('fn'=>'gd_client_portal_collab_table','arg'=>'tasks'));if(!isset($map[$kind]))return 0;$fn=$map[$kind]['fn'];$t=function_exists($fn)?call_user_func($fn,$map[$kind]['arg']):'';if(!$t)return 0;list($where,$args)=$this->scope_sql('tenant_id',$scope);$place=implode(',',array_fill(0,count($statuses),'%s'));$where.=($where?' AND':' WHERE')." status NOT IN ($place)";$args=array_merge($args,$statuses);return (int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM $t$where",$args)); }
    public function monthly_revenue($scope,$start){ global $wpdb;$out=array();$t=function_exists('gd_client_portal_billing_invoices_table')?gd_client_portal_billing_invoices_table():'';if(!$t)return $out;$where=' WHERE created_at >= %s';$args=array($start.' 00:00:00');if(empty($scope['global'])){$where.=' AND tenant_id=%d';$args[]=absint($scope['tenant_id']??0);}$rows=$wpdb->get_results($wpdb->prepare("SELECT DATE_FORMAT(created_at,'%%Y-%%m') ym,COALESCE(SUM(total),0) total FROM $t$where GROUP BY ym ORDER BY ym ASC",$args));foreach((array)$rows as $r)$out[$r->ym]=(float)$r->total;return $out; }
    public function latest_currency(){ global $wpdb;$t=function_exists('gd_client_portal_billing_invoices_table')?gd_client_portal_billing_invoices_table():'';if(!$t)return ''; $row=$wpdb->get_row('SELECT currency FROM '.$t.' WHERE currency IS NOT NULL AND currency<>"" ORDER BY id DESC LIMIT 1');return $row?(string)$row->currency:''; }
}
