<?php
/** GD Client Portal v3.9 — Executive Analytics & Unified Dashboard. */
if(!defined('ABSPATH')) exit;

function gd_client_portal_exec_scope(){
    if(gd_client_portal_is_platform_admin()) return array('tenant_id'=>0,'global'=>true);
    $tenant=absint(gd_client_portal_get_current_tenant_id());
    return array('tenant_id'=>$tenant,'global'=>false);
}
function gd_client_portal_exec_projects(){
    $projects=gd_client_portal_get_visible_projects();
    if(gd_client_portal_is_platform_admin()) return is_array($projects)?$projects:array();
    $tenant=absint(gd_client_portal_get_current_tenant_id()); if($tenant<=0)return array();
    return array_values(array_filter((array)$projects,function($p)use($tenant){return absint($p->tenant_id)===$tenant;}));
}
function gd_client_portal_exec_money($amount,$currency='GHS'){return number_format((float)$amount,2).' '.strtoupper($currency?:'GHS');}
function gd_client_portal_exec_metrics(){
    $scope=gd_client_portal_exec_scope(); $projects=gd_client_portal_exec_projects();
    $m=array('projects'=>count($projects),'active'=>0,'completed'=>0,'overdue'=>0,'at_risk'=>0,'unassigned'=>0,'revenue'=>0,'paid'=>0,'outstanding'=>0,'invoices'=>0,'open_tickets'=>0,'overdue_tickets'=>0,'avg_rating'=>0,'recommend'=>0,'reviews'=>0,'contracts'=>0,'documents'=>0,'tasks_open'=>0);
    foreach($projects as $p){$done=in_array($p->status,array('completed','closed'),true)||in_array($p->current_stage,array('completed','final_delivery'),true);$done?$m['completed']++:$m['active']++;if(function_exists('gd_client_portal_get_sla')){$sla=gd_client_portal_get_sla($p->id);if($sla){$ss=gd_client_portal_sla_status($sla);if($ss==='overdue')$m['overdue']++;elseif($ss==='at_risk')$m['at_risk']++;}}if(function_exists('gd_client_portal_get_project_lead')&&!gd_client_portal_get_project_lead($p->id))$m['unassigned']++;}
    $svc=gdcp_executive_service();$m=array_merge($m,$svc->financial_metrics($scope),$svc->support_metrics($scope),$svc->feedback_metrics($scope));$m['contracts']=$svc->accepted_contracts($scope);$m['documents']=$svc->documents($scope);$m['tasks_open']=$svc->open_tasks($scope);return $m;
}
function gd_client_portal_exec_monthly_revenue(){
    $scope=gd_client_portal_exec_scope();$out=array();$start=gmdate('Y-m-01',strtotime('-5 months'));for($i=0;$i<6;$i++){$key=gmdate('Y-m',strtotime($start." +$i months"));$out[$key]=0;}foreach((array)gdcp_executive_service()->monthly_revenue($scope,$start) as $month=>$value)if(isset($out[$month]))$out[$month]=(float)$value;return $out;
}
function gd_client_portal_exec_health($m){$score=100;if($m['overdue']>0)$score-=min(30,$m['overdue']*8);if($m['at_risk']>0)$score-=min(20,$m['at_risk']*5);if($m['unassigned']>0)$score-=min(15,$m['unassigned']*3);if($m['overdue_tickets']>0)$score-=min(15,$m['overdue_tickets']*5);if($m['outstanding']>0&&$m['revenue']>0&&($m['outstanding']/$m['revenue'])>.25)$score-=10;if($m['reviews']>0&&$m['avg_rating']<3.5)$score-=10;$score=max(0,min(100,$score));return array('score'=>$score,'label'=>$score>=80?'Healthy':($score>=60?'Watch':'At risk'));}
function gd_client_portal_render_executive($atts=array()){
    if(!gd_client_portal_verify_request()||!gd_client_portal_verify_tenant_access())return gd_client_portal_render_access_gate(__('Executive Dashboard','gd-client-portal'),__('Please sign in to view analytics.','gd-client-portal'));wp_enqueue_style('gd-client-portal-executive');wp_enqueue_script('gd-client-portal-executive');$m=gd_client_portal_exec_metrics();$health=gd_client_portal_exec_health($m);$monthly=gd_client_portal_exec_monthly_revenue();$scope=gd_client_portal_exec_scope();$currency=gdcp_executive_service()->latest_currency()?:'GHS';
    ob_start();echo '<div class="gd-executive"><header class="gd-executive-hero"><div><span>GD CLIENT PORTAL · EXECUTIVE INTELLIGENCE</span><h2>Executive Dashboard</h2><p>Unified operational, financial and client-experience performance.</p></div><div class="gd-exec-health"><b>'.intval($health['score']).'</b><span>'.esc_html($health['label']).'</span><small>Portfolio health</small></div></header>';
    echo '<section class="gd-exec-grid">';$cards=array(array('projects','Projects',$m['projects']),array('active','Active projects',$m['active']),array('completed','Completed',$m['completed']),array('revenue','Revenue',gd_client_portal_exec_money($m['revenue'],$currency)),array('paid','Collected',gd_client_portal_exec_money($m['paid'],$currency)),array('outstanding','Outstanding',gd_client_portal_exec_money($m['outstanding'],$currency)),array('tickets','Open tickets',$m['open_tickets']),array('rating','Client rating',number_format_i18n($m['avg_rating'],1).'/5'));foreach($cards as $c)echo '<div class="gd-exec-card metric-'.esc_attr($c[0]).'"><small>'.esc_html($c[1]).'</small><strong>'.esc_html($c[2]).'</strong></div>';echo '</section>';
    echo '<section class="gd-exec-panels"><div class="gd-exec-panel"><div class="gd-exec-panel-head"><h3>Revenue trend</h3><span>'.esc_html($currency).'</span></div><div class="gd-exec-chart">';$max=max(1,max($monthly));foreach($monthly as $month=>$value){$pct=round(($value/$max)*100);echo '<div class="gd-exec-bar"><div class="gd-exec-bar-value">'.esc_html(number_format_i18n($value,0)).'</div><div class="gd-exec-bar-track"><i style="height:'.intval(max(4,$pct)).'%"></i></div><small>'.esc_html(wp_date('M',strtotime($month.'-01'))).'</small></div>';}echo '</div></div>';
    echo '<div class="gd-exec-panel"><div class="gd-exec-panel-head"><h3>Operational pulse</h3><span>Live</span></div><div class="gd-exec-pulse"><div><b>'.intval($m['overdue']).'</b><span>Overdue projects</span></div><div><b>'.intval($m['at_risk']).'</b><span>At-risk projects</span></div><div><b>'.intval($m['unassigned']).'</b><span>Unassigned projects</span></div><div><b>'.intval($m['overdue_tickets']).'</b><span>Overdue tickets</span></div><div><b>'.intval($m['tasks_open']).'</b><span>Open tasks</span></div><div><b>'.intval($m['recommend']).'%</b><span>Would recommend</span></div></div></div></section>';
    echo '<section class="gd-exec-panel"><div class="gd-exec-panel-head"><h3>Executive snapshot</h3><span>'.($scope['global']?'All tenants':'Current tenant').'</span></div><div class="gd-exec-insights"><div><strong>Delivery</strong><p>'.intval($m['active']).' active projects with '.intval($m['overdue']).' overdue and '.intval($m['at_risk']).' at risk.</p></div><div><strong>Finance</strong><p>'.esc_html(gd_client_portal_exec_money($m['outstanding'],$currency)).' remains outstanding across '.intval($m['invoices']).' invoices.</p></div><div><strong>Client experience</strong><p>'.($m['reviews']?esc_html(number_format_i18n($m['avg_rating'],2).'/5 from '.$m['reviews'].' reviews and '.$m['recommend'].'% recommendation rate.'):'No published feedback yet.').'</p></div><div><strong>Response</strong><p>'.intval($m['open_tickets']).' open support tickets; '.intval($m['overdue_tickets']).' have breached their SLA.</p></div></div></section></div>';return ob_get_clean();
}
add_shortcode('gd_executive_dashboard','gd_client_portal_render_executive');add_shortcode('gd_executive_analytics','gd_client_portal_render_executive');
add_action('init',function(){if(function_exists('gd_client_portal_register_dashboard_view'))gd_client_portal_register_dashboard_view('executive','gd_client_portal_render_executive');});
function gd_client_portal_register_executive_assets(){wp_register_style('gd-client-portal-executive',GD_CLIENT_PORTAL_URL.'assets/executive.css',array('gd-client-portal'),GD_CLIENT_PORTAL_VERSION);wp_register_script('gd-client-portal-executive',GD_CLIENT_PORTAL_URL.'assets/executive.js',array(),GD_CLIENT_PORTAL_VERSION,true);}add_action('wp_enqueue_scripts','gd_client_portal_register_executive_assets');add_action('admin_enqueue_scripts','gd_client_portal_register_executive_assets');
function gd_client_portal_executive_admin(){if(!gd_client_portal_user_can_access_admin())wp_die(esc_html__('You do not have permission to access this page.','gd-client-portal'));echo '<div class="wrap gd-executive-admin">'.gd_client_portal_render_executive().'</div>';}
function gd_client_portal_register_executive_menu(){add_submenu_page('gd-client-portal',__('Executive Dashboard','gd-client-portal'),__('Executive Dashboard','gd-client-portal'),'gd_client_portal_access_admin','gd-client-portal-executive','gd_client_portal_executive_admin');}add_action('admin_menu','gd_client_portal_register_executive_menu',20);
