<?php
/** GD Client Portal v3.8 — Client Feedback, Reviews & Satisfaction Center. */
if(!defined('ABSPATH')) exit;

function gd_client_portal_feedback_table($s){global $wpdb;return $wpdb->prefix.'gd_feedback_'.$s;}
function gd_client_portal_feedback_install(){global $wpdb;require_once ABSPATH.'wp-admin/includes/upgrade.php';$c=$wpdb->get_charset_collate();$r=gd_client_portal_feedback_table('reviews');$f=gd_client_portal_feedback_table('responses');
 dbDelta("CREATE TABLE $r (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,tenant_id bigint(20) unsigned NOT NULL DEFAULT 0,user_id bigint(20) unsigned NOT NULL DEFAULT 0,project_id bigint(20) unsigned NOT NULL DEFAULT 0,ticket_id bigint(20) unsigned NOT NULL DEFAULT 0,rating tinyint(1) unsigned NOT NULL DEFAULT 0,service_rating tinyint(1) unsigned NOT NULL DEFAULT 0,communication_rating tinyint(1) unsigned NOT NULL DEFAULT 0,timeliness_rating tinyint(1) unsigned NOT NULL DEFAULT 0,comment text NOT NULL,recommend tinyint(1) NOT NULL DEFAULT 0,status varchar(20) NOT NULL DEFAULT 'published',created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY tenant_id(tenant_id),KEY user_id(user_id),KEY project_id(project_id),KEY ticket_id(ticket_id),KEY rating(rating),KEY status(status),UNIQUE KEY project_user(project_id,user_id),UNIQUE KEY ticket_user(ticket_id,user_id)) $c;");
 dbDelta("CREATE TABLE $f (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,review_id bigint(20) unsigned NOT NULL,tenant_id bigint(20) unsigned NOT NULL DEFAULT 0,author_id bigint(20) unsigned NOT NULL DEFAULT 0,body text NOT NULL,is_internal tinyint(1) NOT NULL DEFAULT 0,created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY review_id(review_id),KEY tenant_id(tenant_id),KEY author_id(author_id)) $c;");
}
function gd_client_portal_feedback_upgrade(){if(absint(get_option('gd_client_portal_feedback_schema_version',0))<1){gd_client_portal_feedback_install();update_option('gd_client_portal_feedback_schema_version',1);}}
// Schema lifecycle is managed centrally by GDCP_Migration_Manager (v6.8+).
function gd_client_portal_feedback_review($id){return gdcp_feedback_service()->get_review_for_access($id);}
function gd_client_portal_feedback_projects(){ $rows=gd_client_portal_get_visible_projects();$out=array();foreach($rows as $p){if(gd_client_portal_is_platform_admin()||gd_client_portal_verify_project_access($p))$out[]=$p;}return $out;}
function gd_client_portal_feedback_can_manage($tenant_id=0){if(gd_client_portal_is_platform_admin())return true;return gd_client_portal_user_is_tenant_admin()&&absint(gd_client_portal_get_current_tenant_id())===absint($tenant_id);}
function gd_client_portal_feedback_existing($project_id,$ticket_id=0,$user_id=0){return gdcp_feedback_service()->existing($project_id,$ticket_id,$user_id);}
function gd_client_portal_feedback_create_ajax(){if(!is_user_logged_in()||!gd_client_portal_verify_request())wp_send_json_error(array('message'=>'Access denied.'),403);check_ajax_referer('gd_client_portal_feedback','nonce');$project_id=absint($_POST['project_id']??0);$ticket_id=absint($_POST['ticket_id']??0);$project=$project_id?gd_client_portal_get_project_by_id($project_id):false;$tenant=absint(gd_client_portal_get_current_tenant_id());
 if($project){if(!gd_client_portal_verify_project_access($project))wp_send_json_error(array('message'=>'Project access denied.'),403);if(absint($project->user_id)!==gd_client_portal_cached_current_user_id()&&!gd_client_portal_is_platform_admin()&&!gd_client_portal_user_is_tenant_admin())wp_send_json_error(array('message'=>'Only the client can submit project feedback.'),403);$tenant=absint($project->tenant_id);}
 if($ticket_id&&function_exists('gd_client_portal_support_ticket')){$ticket=gd_client_portal_support_ticket($ticket_id);if(!$ticket||absint($ticket->user_id)!==gd_client_portal_cached_current_user_id())wp_send_json_error(array('message'=>'Ticket access denied.'),403);$ticket_tenant=absint($ticket->tenant_id);if($tenant>0&&$ticket_tenant!==$tenant)wp_send_json_error(array('message'=>'Ticket tenant mismatch.'),403);$tenant=$ticket_tenant;if(!$project_id)$project_id=absint($ticket->project_id);elseif(absint($ticket->project_id)!==$project_id)wp_send_json_error(array('message'=>'Ticket and project do not match.'),403);if($project_id&&$project){if(absint($project->tenant_id)!==$ticket_tenant||absint($project->user_id)!==absint($ticket->user_id))wp_send_json_error(array('message'=>'Ticket and project access denied.'),403);}}
 if($tenant<=0&&!gd_client_portal_is_platform_admin())wp_send_json_error(array('message'=>'No tenant assigned.'),403);
 if(gd_client_portal_feedback_existing($project_id,$ticket_id))wp_send_json_error(array('message'=>'Feedback has already been submitted for this item.'));
 $rating=max(1,min(5,absint($_POST['rating']??0)));$sr=max(0,min(5,absint($_POST['service_rating']??$rating)));$cr=max(0,min(5,absint($_POST['communication_rating']??$rating)));$tr=max(0,min(5,absint($_POST['timeliness_rating']??$rating)));$comment=sanitize_textarea_field(wp_unslash($_POST['comment']??''));$recommend=!empty($_POST['recommend'])?1:0;if(!$rating||!$comment)wp_send_json_error(array('message'=>'Rating and feedback are required.'));$id=gdcp_feedback_service()->submit(array('tenant_id'=>$tenant,'user_id'=>gd_client_portal_cached_current_user_id(),'project_id'=>$project_id,'ticket_id'=>$ticket_id,'rating'=>$rating,'service_rating'=>$sr,'communication_rating'=>$cr,'timeliness_rating'=>$tr,'comment'=>$comment,'recommend'=>$recommend));if(is_wp_error($id))wp_send_json_error(array('message'=>$id->get_error_message()),400);$id=absint($id);
 if(function_exists('gd_client_portal_create_notification')){foreach(gd_client_portal_feedback_managers($tenant) as $uid)gd_client_portal_create_notification($uid,'New client feedback',$project?$project->title:__('A support ticket','gd-client-portal'),'feedback',$project_id,$tenant);}
 if(function_exists('gd_client_portal_audit_log'))gd_client_portal_audit_log('feedback_submitted',$project?$project->title:__('Client feedback','gd-client-portal'),$project_id,$tenant,$comment,'feedback',$id,array('rating'=>$rating,'recommend'=>$recommend,'ticket_id'=>$ticket_id));
 do_action('gd_client_portal_feedback_submitted',$id,$project_id,$ticket_id);wp_send_json_success(array('message'=>'Thank you. Your feedback has been submitted.','id'=>$id));}
add_action('wp_ajax_gd_client_portal_feedback_create','gd_client_portal_feedback_create_ajax');
function gd_client_portal_feedback_managers($tenant){$users=get_users(array('meta_key'=>'gd_client_portal_tenant_id','meta_value'=>absint($tenant),'fields'=>'ID','number'=>100));$out=array();foreach($users as $uid)if(user_can($uid,'gd_client_portal_tenant_admin'))$out[]=absint($uid);if(gd_client_portal_is_platform_admin())$out[]=gd_client_portal_cached_current_user_id();return array_values(array_unique(array_filter($out)));}
function gd_client_portal_feedback_response_ajax(){if(!is_user_logged_in()||!gd_client_portal_verify_request()||!(gd_client_portal_is_platform_admin()||gd_client_portal_user_is_tenant_admin()))wp_send_json_error(array('message'=>'Permission denied.'),403);check_ajax_referer('gd_client_portal_feedback_admin','nonce');$id=absint($_POST['review_id']??0);$r=gd_client_portal_feedback_review($id);if(!$r||!gd_client_portal_feedback_can_manage($r->tenant_id))wp_send_json_error(array('message'=>'Feedback access denied.'),403);$body=sanitize_textarea_field(wp_unslash($_POST['body']??''));$internal=!empty($_POST['internal'])?1:0;if(!$body)wp_send_json_error(array('message'=>'Response is required.'));$response_id=gdcp_feedback_service()->respond($id,$r->tenant_id,gd_client_portal_cached_current_user_id(),$body,$internal);if(is_wp_error($response_id))wp_send_json_error(array('message'=>$response_id->get_error_message()),400);if(!$internal&&function_exists('gd_client_portal_create_notification'))gd_client_portal_create_notification($r->user_id,'Response to your feedback',$body,'feedback',$r->project_id,$r->tenant_id);if(function_exists('gd_client_portal_audit_log'))gd_client_portal_audit_log('feedback_response',$r->project_id?'Project feedback':'Client feedback',$r->project_id,$r->tenant_id,$body,'feedback',$id,array('internal'=>$internal));wp_send_json_success(array('message'=>'Response saved.'));}
add_action('wp_ajax_gd_client_portal_feedback_response','gd_client_portal_feedback_response_ajax');
function gd_client_portal_feedback_data($limit=100){global $wpdb;$w=array();$p=array();if(!gd_client_portal_is_platform_admin()){$tenant=absint(gd_client_portal_get_current_tenant_id());if($tenant<=0)return array();$w[]='tenant_id=%d';$p[]=$tenant;if(!gd_client_portal_user_is_tenant_admin()){$w[]='user_id=%d';$p[]=gd_client_portal_cached_current_user_id();}}$sql='SELECT * FROM '.gd_client_portal_feedback_table('reviews').($w?' WHERE '.implode(' AND ',$w):'').' ORDER BY created_at DESC LIMIT %d';$p[]=max(1,min(300,absint($limit)));return $wpdb->get_results($wpdb->prepare($sql,$p));}
function gd_client_portal_feedback_metrics(){global $wpdb;$w='';$p=array();if(!gd_client_portal_is_platform_admin()){$tenant=absint(gd_client_portal_get_current_tenant_id());if($tenant<=0)return array('count'=>0,'avg'=>0,'recommend'=>0);$w=' WHERE tenant_id=%d';$p[]=$tenant;} $t=gd_client_portal_feedback_table('reviews');$row=$wpdb->get_row($p?$wpdb->prepare("SELECT COUNT(*) count, AVG(rating) avg, AVG(recommend)*100 recommend FROM $t$w AND status='published'",$p):"SELECT COUNT(*) count, AVG(rating) avg, AVG(recommend)*100 recommend FROM $t WHERE status='published'");return array('count'=>intval($row->count),'avg'=>round(floatval($row->avg),2),'recommend'=>round(floatval($row->recommend),1));}
function gd_client_portal_render_feedback($atts=array()){if(!gd_client_portal_verify_request())return gd_client_portal_render_access_gate(__('Feedback Center','gd-client-portal'),__('Please sign in to view feedback.','gd-client-portal'));wp_enqueue_style('gd-client-portal-feedback');wp_enqueue_script('gd-client-portal-feedback');$projects=gd_client_portal_feedback_projects();$reviews=gd_client_portal_feedback_data(50);$metrics=gd_client_portal_feedback_metrics();$nonce=wp_create_nonce('gd_client_portal_feedback');ob_start();echo '<div class="gd-feedback" data-nonce="'.esc_attr($nonce).'" data-admin-nonce="'.esc_attr(wp_create_nonce('gd_client_portal_feedback_admin')).'"><div class="gd-feedback-hero"><div><span>CLIENT PORTAL · V3.8</span><h2>Feedback & Satisfaction</h2><p>Share your experience so we can improve service quality and delivery.</p></div><div class="gd-feedback-score"><strong>'.esc_html(number_format_i18n($metrics['avg'],1)).'</strong><small>average rating</small></div></div>';
 echo '<div class="gd-feedback-metrics"><div><strong>'.intval($metrics['count']).'</strong><span>Reviews</span></div><div><strong>'.esc_html(number_format_i18n($metrics['recommend'],0)).'%</strong><span>Would recommend</span></div><div><strong>5</strong><span>Max rating</span></div></div>';
 $eligible=array();foreach($projects as $p)if(!$p->current_stage||in_array($p->current_stage,array('completed','final_delivery','approval'),true))$eligible[]=$p;echo '<section class="gd-feedback-card"><div class="gd-feedback-head"><div><h3>Share your feedback</h3><p>Tell us what went well and what we can improve.</p></div></div><div class="gd-feedback-form"><select id="gd-feedback-project"><option value="0">Select a completed project</option>';foreach($eligible as $p)echo '<option value="'.intval($p->id).'">'.esc_html($p->title).'</option>';echo '</select><div class="gd-feedback-ticket-wrap"><small>Or rate a resolved support ticket</small><select id="gd-feedback-ticket"><option value="0">Select a resolved ticket (optional)</option>';if(function_exists('gd_client_portal_support_tickets')){foreach(gd_client_portal_support_tickets(100) as $t)if(in_array($t->status,array('resolved','closed'),true))echo '<option value="'.intval($t->id).'">'.esc_html($t->subject).'</option>';}echo '</select></div><div class="gd-stars" role="radiogroup" aria-label="Overall rating">';for($i=1;$i<=5;$i++)echo '<button type="button" data-rating="'.intval($i).'" aria-label="'.intval($i).' stars">★</button>';echo '</div><div class="gd-feedback-subratings"><label>Service<select id="gd-feedback-service"><option>5</option><option>4</option><option>3</option><option>2</option><option>1</option></select></label><label>Communication<select id="gd-feedback-communication"><option>5</option><option>4</option><option>3</option><option>2</option><option>1</option></select></label><label>Timeliness<select id="gd-feedback-timeliness"><option>5</option><option>4</option><option>3</option><option>2</option><option>1</option></select></label></div><textarea id="gd-feedback-comment" placeholder="What did you like? What could we improve?"></textarea><label class="gd-feedback-check"><input type="checkbox" id="gd-feedback-recommend"> I would recommend this service</label><button class="gd-feedback-primary" id="gd-feedback-submit">Submit feedback</button><span id="gd-feedback-result"></span></div></section>';
 echo '<section class="gd-feedback-card"><div class="gd-feedback-head"><div><h3>Your feedback history</h3><p>Previously submitted ratings and responses.</p></div></div><div class="gd-feedback-list">';foreach($reviews as $r){$p=$r->project_id?gd_client_portal_get_project_by_id($r->project_id):false;echo '<article><div class="gd-feedback-rating">'.str_repeat('★',intval($r->rating)).str_repeat('☆',5-intval($r->rating)).'</div><strong>'.esc_html($p?$p->title:($r->ticket_id?'Support ticket':'Portal experience')).'</strong><time>'.esc_html(wp_date(get_option('date_format'),strtotime($r->created_at))).'</time><p>'.nl2br(esc_html($r->comment)).'</p>';global $wpdb;$responses=$wpdb->get_results($wpdb->prepare('SELECT * FROM '.gd_client_portal_feedback_table('responses').' WHERE review_id=%d AND is_internal=0 ORDER BY created_at ASC',$r->id));foreach($responses as $resp)echo '<div class="gd-feedback-response"><small>Team response</small><p>'.nl2br(esc_html($resp->body)).'</p></div>';echo '</article>';}if(!$reviews)echo '<div class="gd-feedback-empty">No feedback submitted yet.</div>';echo '</div></section></div>';return ob_get_clean();}
add_shortcode('gd_feedback','gd_client_portal_render_feedback');add_shortcode('gd_reviews','gd_client_portal_render_feedback');add_shortcode('gd_satisfaction_center','gd_client_portal_render_feedback');
add_action('init',function(){if(function_exists('gd_client_portal_register_dashboard_view'))gd_client_portal_register_dashboard_view('feedback','gd_client_portal_render_feedback');});
function gd_client_portal_register_feedback_assets(){wp_register_style('gd-client-portal-feedback',GD_CLIENT_PORTAL_URL.'assets/feedback.css',array('gd-client-portal'),GD_CLIENT_PORTAL_VERSION);wp_register_script('gd-client-portal-feedback',GD_CLIENT_PORTAL_URL.'assets/feedback.js',array(),GD_CLIENT_PORTAL_VERSION,true);}add_action('wp_enqueue_scripts','gd_client_portal_register_feedback_assets');add_action('admin_enqueue_scripts','gd_client_portal_register_feedback_assets');
function gd_client_portal_feedback_admin(){if(!gd_client_portal_user_can_access_admin())wp_die('Access denied.');$reviews=gd_client_portal_feedback_data(200);$metrics=gd_client_portal_feedback_metrics();echo '<div class="wrap gd-feedback-admin"><h1>Feedback & Satisfaction</h1><p>Monitor client satisfaction, reviews and service quality.</p><div class="gd-feedback-admin-metrics"><div><strong>'.intval($metrics['count']).'</strong><span>Total reviews</span></div><div><strong>'.esc_html(number_format_i18n($metrics['avg'],2)).'/5</strong><span>Average rating</span></div><div><strong>'.esc_html(number_format_i18n($metrics['recommend'],0)).'%</strong><span>Recommendation</span></div></div><table class="widefat striped"><thead><tr><th>Date</th><th>Client</th><th>Project</th><th>Rating</th><th>Recommendation</th><th>Feedback</th></tr></thead><tbody>';foreach($reviews as $r){$u=gd_client_portal_cached_user($r->user_id);$p=$r->project_id?gd_client_portal_get_project_by_id($r->project_id):false;echo '<tr><td>'.esc_html($r->created_at).'</td><td>'.esc_html($u?$u->display_name:'User #'.$r->user_id).'</td><td>'.esc_html($p?$p->title:($r->ticket_id?'Support ticket':'General')).'</td><td><strong>'.intval($r->rating).'/5</strong></td><td>'.($r->recommend?'Yes':'No').'</td><td>'.esc_html(wp_trim_words($r->comment,24)).'</td></tr>';}if(!$reviews)echo '<tr><td colspan="6">No feedback found.</td></tr>';echo '</tbody></table></div>';}
function gd_client_portal_register_feedback_admin(){add_submenu_page('gd-client-portal','Feedback & Satisfaction','Feedback & Satisfaction','gd_client_portal_access_admin','gd-client-portal-feedback','gd_client_portal_feedback_admin');}add_action('admin_menu','gd_client_portal_register_feedback_admin',20);
