<?php
if(!defined('ABSPATH')) exit;

class GDCP_Feedback_Repository {
    public function reviews_table(){ return gd_client_portal_feedback_table('reviews'); }
    public function responses_table(){ return gd_client_portal_feedback_table('responses'); }
    public function find_review($id,$lock=false){ global $wpdb; $sql='SELECT * FROM '.$this->reviews_table().' WHERE id=%d LIMIT 1'; if($lock)$sql.=' FOR UPDATE'; return $wpdb->get_row($wpdb->prepare($sql,absint($id))); }
    public function find_existing($project_id,$ticket_id=0,$user_id=0){ global $wpdb; $user_id=$user_id?:gd_client_portal_cached_current_user_id(); $where=$ticket_id?'ticket_id=%d AND user_id=%d':'project_id=%d AND user_id=%d'; return $wpdb->get_row($wpdb->prepare('SELECT * FROM '.$this->reviews_table().' WHERE '.$where.' LIMIT 1',$ticket_id?:$project_id,$user_id)); }
    public function insert_review(array $data){ global $wpdb; $fields=array('tenant_id'=>'%d','user_id'=>'%d','project_id'=>'%d','ticket_id'=>'%d','rating'=>'%d','service_rating'=>'%d','communication_rating'=>'%d','timeliness_rating'=>'%d','comment'=>'%s','recommend'=>'%d','status'=>'%s','created_at'=>'%s','updated_at'=>'%s'); $row=array();$fmt=array();foreach($fields as $k=>$f){if(array_key_exists($k,$data)){$row[$k]=$data[$k];$fmt[]=$f;}} $ok=$wpdb->insert($this->reviews_table(),$row,$fmt); return $ok===false?new WP_Error('feedback_insert_failed',$wpdb->last_error?:'Unable to save feedback.'):absint($wpdb->insert_id); }
    public function insert_response(array $data){ global $wpdb; $fields=array('review_id'=>'%d','tenant_id'=>'%d','author_id'=>'%d','body'=>'%s','is_internal'=>'%d','created_at'=>'%s');$row=array();$fmt=array();foreach($fields as $k=>$f){if(array_key_exists($k,$data)){$row[$k]=$data[$k];$fmt[]=$f;}}$ok=$wpdb->insert($this->responses_table(),$row,$fmt);return $ok===false?new WP_Error('feedback_response_insert_failed',$wpdb->last_error?:'Unable to save response.'):absint($wpdb->insert_id);}
    public function find_latest_for_project($project_id){global $wpdb; return $wpdb->get_row($wpdb->prepare('SELECT * FROM '.$this->reviews_table().' WHERE project_id=%d ORDER BY id DESC LIMIT 1',absint($project_id)));}
    public function list_reviews($limit=100,$tenant_id=0,$user_id=0){global $wpdb;$w=array();$p=array();if($tenant_id){$w[]='tenant_id=%d';$p[]=$tenant_id;}if($user_id){$w[]='user_id=%d';$p[]=$user_id;}$p[]=max(1,min(300,absint($limit)));$sql='SELECT * FROM '.$this->reviews_table().($w?' WHERE '.implode(' AND ',$w):'').' ORDER BY created_at DESC LIMIT %d';return $wpdb->get_results($wpdb->prepare($sql,$p));}
    public function metrics($tenant_id=0){global $wpdb;$where=" WHERE status='published'";$args=array();if($tenant_id){$where.=' AND tenant_id=%d';$args[]=$tenant_id;}$sql="SELECT COUNT(*) count, AVG(rating) avg, AVG(recommend)*100 recommend FROM ".$this->reviews_table().$where;return $wpdb->get_row($args?$wpdb->prepare($sql,$args):$sql);}
    public function list_public_responses($review_id){global $wpdb;return $wpdb->get_results($wpdb->prepare('SELECT * FROM '.$this->responses_table().' WHERE review_id=%d AND is_internal=0 ORDER BY created_at ASC',absint($review_id)));}
}
