<?php
/** GD Client Portal v4.3 - Workflow Governance & Observability. */
if (!defined('ABSPATH')) exit;
function gd_client_portal_governance_table(){global $wpdb;return $wpdb->prefix.'gd_portal_automation_versions';}
function gd_client_portal_governance_activate(){global $wpdb;require_once ABSPATH.'wp-admin/includes/upgrade.php';$c=$wpdb->get_charset_collate();$t=gd_client_portal_governance_table();dbDelta("CREATE TABLE {$t} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, rule_id bigint(20) unsigned NOT NULL, version_no int unsigned NOT NULL DEFAULT 1, change_type varchar(30) NOT NULL DEFAULT 'snapshot', name varchar(190) NOT NULL, event_key varchar(100) NOT NULL, conditions longtext NULL, actions longtext NULL, status varchar(20) NOT NULL DEFAULT 'active', changed_by bigint(20) unsigned NOT NULL DEFAULT 0, created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), UNIQUE KEY rule_version(rule_id,version_no), KEY rule_id(rule_id), KEY version_no(version_no), KEY created_at(created_at)) {$c};");update_option('gd_client_portal_governance_schema_version',1,false);}
add_action('plugins_loaded',function(){if(absint(get_option('gd_client_portal_governance_schema_version',0))<1)gd_client_portal_governance_activate();},31);
function gd_client_portal_automation_snapshot_rule($rule_id,$change_type='snapshot'){global $wpdb;$rule_id=absint($rule_id);if(!$rule_id)return false;$rt=gd_client_portal_automation_table('rules');$t=gd_client_portal_governance_table();$wpdb->query('START TRANSACTION');try{$rule=function_exists('gdcp_automation_service')?gdcp_automation_service()->get_rule($rule_id):null;if(!$rule){$wpdb->query('ROLLBACK');return false;}$next=(int)$wpdb->get_var($wpdb->prepare("SELECT COALESCE(MAX(version_no),0)+1 FROM {$t} WHERE rule_id=%d",$rule_id));$ok=$wpdb->insert($t,array('rule_id'=>$rule_id,'version_no'=>$next,'change_type'=>sanitize_key($change_type),'name'=>$rule->name,'event_key'=>$rule->event_key,'conditions'=>$rule->conditions,'actions'=>$rule->actions,'status'=>$rule->status,'changed_by'=>gd_client_portal_cached_current_user_id(),'created_at'=>current_time('mysql')),array('%d','%d','%s','%s','%s','%s','%s','%s','%s','%d','%s'));if(!$ok){$wpdb->query('ROLLBACK');return false;}$wpdb->query('COMMIT');return true;}catch(\Throwable $e){$wpdb->query('ROLLBACK');return false;}}
function gd_client_portal_governance_restore($version_id){if(!gd_client_portal_user_can_access_admin())return false;global $wpdb;$t=gd_client_portal_governance_table();$v=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$t} WHERE id=%d",absint($version_id)));if(!$v||!function_exists('gdcp_automation_service'))return false;$ok=gdcp_automation_service()->restore_rule($v->rule_id,array('name'=>$v->name,'event_key'=>$v->event_key,'conditions'=>$v->conditions,'actions'=>$v->actions));if($ok){gd_client_portal_automation_snapshot_rule($v->rule_id,'restored');return true;}return false;}
function gd_client_portal_governance_admin(){if(!gd_client_portal_user_can_access_admin())wp_die('Access denied.');global $wpdb;$qt=gd_client_portal_automation_table('queue');$lt=gd_client_portal_automation_table('logs');$rt=gd_client_portal_automation_table('rules');$vt=gd_client_portal_governance_table();
if(isset($_GET['retry_queue'])&&check_admin_referer('gdcp_retry_queue_'.absint($_GET['retry_queue']))){$id=absint($_GET['retry_queue']);$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$qt} WHERE id=%d",$id));if($row){function_exists('gdcp_automation_service') ? gdcp_automation_service()->retry_queue($id) : false;wp_schedule_single_event(time()+5,'gd_client_portal_automation_queue_runner',array($id));}}
if(isset($_GET['restore_version'])&&check_admin_referer('gdcp_restore_version_'.absint($_GET['restore_version']))){gd_client_portal_governance_restore(absint($_GET['restore_version']));}
$rules=function_exists('gdcp_automation_service')?gdcp_automation_service()->list_rules():array();$stats=function_exists('gdcp_automation_service')?gdcp_automation_service()->stats():array();$analytics=function_exists('gdcp_automation_service')?gdcp_automation_service()->analytics(30):array();$queued=(int)($stats['queued']??0);$failed=(int)($stats['failed']??0);$running=(int)($stats['running']??0);$success=(int)($analytics['success']??0);$errors=(int)($analytics['failed']??0);$versions=$wpdb->get_results("SELECT * FROM {$vt} ORDER BY id DESC LIMIT 50");
echo '<div class="wrap"><h1>Workflow Governance &amp; Observability</h1><p>Version control, execution health and operational recovery for automation workflows.</p><div style="display:flex;gap:12px;flex-wrap:wrap;margin:18px 0">';foreach(array('Active rules'=>count(array_filter((array)$rules,function($r){return $r->status==='active';})),'Queued'=>$queued,'Running'=>$running,'Failed queue'=>$failed,'Successful runs'=>$success,'Failed runs'=>$errors) as $k=>$v)echo '<div style="background:#fff;border:1px solid #dcdcde;border-radius:8px;padding:16px 22px;min-width:130px"><strong style="font-size:24px">'.intval($v).'</strong><br><span>'.esc_html($k).'</span></div>';echo '</div>';
echo '<h2>Failed / queued actions</h2><table class="widefat striped"><thead><tr><th>ID</th><th>Execution</th><th>Rule</th><th>Project</th><th>Status</th><th>Attempts</th><th>Run at</th><th>Action</th></tr></thead><tbody>';$rows=function_exists('gdcp_automation_service')?gdcp_automation_service()->list_queue_by_status(array('queued','failed','running'),100):array();foreach((array)$rows as $r){$rule=function_exists('gd_client_portal_automation_get_rule')?gd_client_portal_automation_get_rule($r->rule_id):null;$url=wp_nonce_url(admin_url('admin.php?page=gd-client-portal-governance&retry_queue='.$r->id),'gdcp_retry_queue_'.$r->id);echo '<tr><td>'.intval($r->id).'</td><td><code>'.esc_html($r->execution_id).'</code></td><td>'.esc_html($rule?$rule->name:'Deleted workflow').'</td><td>#'.intval($r->project_id).'</td><td>'.esc_html($r->status).'</td><td>'.intval($r->attempts).' / '.intval($r->max_attempts).'</td><td>'.esc_html($r->run_at).'</td><td>'.($r->status==='failed'?'<a class="button" href="'.esc_url($url).'">Retry</a>':'—').'</td></tr>';}if(!$rows)echo '<tr><td colspan="8">No queued or failed actions.</td></tr>';echo '</tbody></table>';
echo '<h2>Workflow version history</h2><table class="widefat striped"><thead><tr><th>Workflow</th><th>Version</th><th>Change</th><th>Trigger</th><th>Status</th><th>Changed by</th><th>Created</th><th></th></tr></thead><tbody>';foreach((array)$versions as $v){$restore=wp_nonce_url(admin_url('admin.php?page=gd-client-portal-governance&restore_version='.$v->id),'gdcp_restore_version_'.$v->id);echo '<tr><td>'.esc_html($v->name).' (#'.intval($v->rule_id).')</td><td>v'.intval($v->version_no).'</td><td>'.esc_html($v->change_type).'</td><td>'.esc_html($v->event_key).'</td><td>'.esc_html($v->status).'</td><td>#'.intval($v->changed_by).'</td><td>'.esc_html($v->created_at).'</td><td><a class="button" href="'.esc_url($restore).'" onclick="return confirm(\'Restore this version? The workflow will be paused.\')">Restore</a></td></tr>';}if(!$versions)echo '<tr><td colspan="8">No version snapshots yet.</td></tr>';echo '</tbody></table></div>';}
add_action('admin_menu',function(){add_submenu_page('gd-client-portal','Workflow Governance','Workflow Governance','gd_client_portal_access_admin','gd-client-portal-governance','gd_client_portal_governance_admin');},22);
