<?php
/** GD Client Portal v3.7 — Client Support & Helpdesk Center. */
if(!defined('ABSPATH')) exit;
function gd_client_portal_support_table($s){global $wpdb;return $wpdb->prefix.'gd_support_'.$s;}
function gd_client_portal_support_install(){global $wpdb;require_once ABSPATH.'wp-admin/includes/upgrade.php';$c=$wpdb->get_charset_collate();$t=gd_client_portal_support_table('tickets');$m=gd_client_portal_support_table('messages');dbDelta("CREATE TABLE $t (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,tenant_id bigint(20) unsigned NOT NULL DEFAULT 0,user_id bigint(20) unsigned NOT NULL DEFAULT 0,project_id bigint(20) unsigned NOT NULL DEFAULT 0,subject varchar(255) NOT NULL,category varchar(40) NOT NULL DEFAULT 'general',priority varchar(20) NOT NULL DEFAULT 'normal',status varchar(30) NOT NULL DEFAULT 'open',assigned_to bigint(20) unsigned NOT NULL DEFAULT 0,due_at datetime NULL,last_response_at datetime NULL,created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,closed_at datetime NULL,PRIMARY KEY(id),KEY tenant_id(tenant_id),KEY user_id(user_id),KEY project_id(project_id),KEY status(status),KEY priority(priority),KEY assigned_to(assigned_to),KEY due_at(due_at)) $c;");dbDelta("CREATE TABLE $m (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,ticket_id bigint(20) unsigned NOT NULL,tenant_id bigint(20) unsigned NOT NULL DEFAULT 0,author_id bigint(20) unsigned NOT NULL DEFAULT 0,body longtext NOT NULL,is_internal tinyint(1) NOT NULL DEFAULT 0,created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY ticket_id(ticket_id),KEY tenant_id(tenant_id),KEY author_id(author_id),KEY is_internal(is_internal),KEY created_at(created_at)) $c;");}
function gd_client_portal_support_upgrade(){if(absint(get_option('gd_client_portal_support_schema_version',0))<1){gd_client_portal_support_install();update_option('gd_client_portal_support_schema_version',1);}}
// Schema lifecycle is managed centrally by GDCP_Migration_Manager (v6.8+).
function gd_client_portal_support_statuses(){return array('open'=>'Open','in_progress'=>'In progress','waiting_client'=>'Waiting for client','resolved'=>'Resolved','closed'=>'Closed');}
function gd_client_portal_support_priorities(){return array('low'=>'Low','normal'=>'Normal','high'=>'High','urgent'=>'Urgent');}
function gd_client_portal_support_categories(){return array('general'=>'General','technical'=>'Technical','billing'=>'Billing','project'=>'Project','account'=>'Account','other'=>'Other');}
function gd_client_portal_support_repository(){static $repo;if(!$repo)$repo=new GDCP_Support_Repository();return $repo;}
function gd_client_portal_support_service(){static $service;if(!$service)$service=new GDCP_Support_Service(gd_client_portal_support_repository());return $service;}
function gd_client_portal_support_ticket($id){return gd_client_portal_support_repository()->find($id);}
function gd_client_portal_support_access($t,$manager=false){if(!$t||!is_user_logged_in()||!gd_client_portal_verify_request())return false;if(gd_client_portal_is_platform_admin())return true;$tenant=absint(gd_client_portal_get_current_tenant_id());if($tenant<=0||absint($t->tenant_id)!==$tenant)return false;return $manager?gd_client_portal_user_is_tenant_admin():absint($t->user_id)===gd_client_portal_cached_current_user_id();}
function gd_client_portal_support_tickets($limit=100){$w=array();$p=array();if(!gd_client_portal_is_platform_admin()){$tenant=absint(gd_client_portal_get_current_tenant_id());if($tenant<=0)return array();$w[]='tenant_id=%d';$p[]=$tenant;if(!gd_client_portal_user_is_tenant_admin()){$w[]='user_id=%d';$p[]=gd_client_portal_cached_current_user_id();}}return gd_client_portal_support_repository()->list_tickets($w,$p,max(1,min(300,absint($limit))));}
function gd_client_portal_support_create_ajax(){gd_client_portal_ajax_guard('gd_client_portal_support','nonce');$tenant=absint(gd_client_portal_get_current_tenant_id());if($tenant<=0&&!gd_client_portal_is_platform_admin())wp_send_json_error(array('message'=>'No tenant assigned.'),403);$project_id=absint($_POST['project_id']??0);if($project_id){$project=gd_client_portal_cached_project($project_id);if(!$project||!gd_client_portal_verify_project_access($project))wp_send_json_error(array('message'=>'Project access denied.'),403);$tenant=absint($project->tenant_id);} $subject=sanitize_text_field(wp_unslash($_POST['subject']??''));$body=sanitize_textarea_field(wp_unslash($_POST['body']??''));$category=sanitize_key($_POST['category']??'general');$priority=sanitize_key($_POST['priority']??'normal');if(!$subject||!$body)wp_send_json_error(array('message'=>'Subject and message are required.'));if(!array_key_exists($category,gd_client_portal_support_categories()))$category='general';if(!array_key_exists($priority,gd_client_portal_support_priorities()))$priority='normal';$id=gd_client_portal_support_service()->create_ticket($tenant,gd_client_portal_cached_current_user_id(),$project_id,$subject,$body,$category,$priority);if(!$id)wp_send_json_error(array('message'=>'Support ticket could not be created.'),500);if(function_exists('gd_client_portal_create_notification')){foreach(gd_client_portal_support_managers($tenant) as $uid)gd_client_portal_create_notification($uid,'New support ticket',$subject,'support_ticket',$project_id,$tenant);}do_action('gd_client_portal_support_ticket_created',$id,$project_id,$tenant);if(function_exists('gd_client_portal_audit_log'))gd_client_portal_audit_log('support_ticket_created',$subject,$project_id,$tenant,$body,'support_ticket',$id,array('priority'=>$priority,'category'=>$category));wp_send_json_success(array('id'=>$id,'message'=>'Support ticket created.'));}
function gd_client_portal_support_managers($tenant){$ids=array();$users=get_users(array('number'=>-1,'fields'=>'ID','meta_key'=>'gd_client_portal_tenant_id','meta_value'=>absint($tenant)));foreach($users as $uid)if(user_can($uid,'gd_client_portal_tenant_admin'))$ids[]=absint($uid);return $ids;}
add_action('wp_ajax_gd_client_portal_support_create','gd_client_portal_support_create_ajax');
function gd_client_portal_support_reply_ajax(){gd_client_portal_ajax_guard('gd_client_portal_support','nonce');$id=absint($_POST['ticket_id']??0);$t=gd_client_portal_support_ticket($id);$manager=gd_client_portal_user_is_tenant_admin()||gd_client_portal_is_platform_admin();if(!$t||!gd_client_portal_support_access($t,$manager))wp_send_json_error(array('message'=>'Ticket access denied.'),403);$body=sanitize_textarea_field(wp_unslash($_POST['body']??''));if(!$body)wp_send_json_error(array('message'=>'Message is required.'));$internal=$manager&&!empty($_POST['internal'])?1:0;if(!gd_client_portal_support_service()->reply($t,gd_client_portal_cached_current_user_id(),$body,$manager,$internal))wp_send_json_error(array('message'=>'Reply could not be saved.'),500);if(!$internal&&function_exists('gd_client_portal_create_notification')){if($manager)gd_client_portal_create_notification($t->user_id,'Support team replied',$t->subject,'support_ticket',$t->project_id,$t->tenant_id);else foreach(gd_client_portal_support_managers($t->tenant_id) as $uid)gd_client_portal_create_notification($uid,'Client replied to support ticket',$t->subject,'support_ticket',$t->project_id,$t->tenant_id);}if(function_exists('gd_client_portal_audit_log'))gd_client_portal_audit_log('support_ticket_replied',$t->subject,$t->project_id,$t->tenant_id,$body,'support_ticket',$id,array('internal'=>$internal));wp_send_json_success(array('message'=>'Reply posted.'));}
add_action('wp_ajax_gd_client_portal_support_reply','gd_client_portal_support_reply_ajax');
function gd_client_portal_support_update_ajax(){gd_client_portal_ajax_guard('gd_client_portal_support_admin','nonce');gd_client_portal_ajax_require_tenant_admin();$id=absint($_POST['ticket_id']??0);$t=gd_client_portal_support_ticket($id);if(!$t||!gd_client_portal_support_access($t,true))wp_send_json_error(array('message'=>'Ticket access denied.'),403);$status=sanitize_key($_POST['status']??'open');$priority=sanitize_key($_POST['priority']??'normal');$assignee=absint($_POST['assigned_to']??0);if(!array_key_exists($status,gd_client_portal_support_statuses())||!array_key_exists($priority,gd_client_portal_support_priorities()))wp_send_json_error(array('message'=>'Invalid ticket values.'));if($assignee){$u=gd_client_portal_cached_user($assignee);$ut=absint(get_user_meta($assignee,'gd_client_portal_tenant_id',true));if(!$u||$ut!==absint($t->tenant_id)||user_can($u,'manage_options'))$assignee=0;}if(!gd_client_portal_support_service()->update_ticket($t,$status,$priority,$assignee))wp_send_json_error(array('message'=>'Ticket update failed.'),500);if(function_exists('gd_client_portal_create_notification'))gd_client_portal_create_notification($t->user_id,'Support ticket updated',sprintf('“%s” is now %s.',$t->subject,gd_client_portal_support_statuses()[$status]),'support_ticket',$t->project_id,$t->tenant_id);if(function_exists('gd_client_portal_audit_log'))gd_client_portal_audit_log('support_ticket_updated',$t->subject,$t->project_id,$t->tenant_id,'','support_ticket',$id,array('status'=>$status,'priority'=>$priority,'assigned_to'=>$assignee));wp_send_json_success(array('message'=>'Ticket updated.'));}
add_action('wp_ajax_gd_client_portal_support_update','gd_client_portal_support_update_ajax');
function gd_client_portal_support_messages($id,$internal=false){return gd_client_portal_support_repository()->messages($id,$internal);}
function gd_client_portal_render_support(){
    gd_client_portal_enqueue_support_assets();
    if(!is_user_logged_in()||!gd_client_portal_verify_request()) return '<div class="gd-support-gate">Please log in to access Support.</div>';
    $ticket_id=absint($_GET['support_ticket']??0); $tickets=gd_client_portal_support_tickets(100); ob_start();
    ?>
    <div class="gd-support">
      <header class="gd-support-hero"><div><span>GD CLIENT PORTAL · V3.7</span><h2>Support &amp; Helpdesk</h2><p>Get help, track responses and keep every support conversation connected to your portal.</p></div><button class="gd-support-new" type="button" id="gd-support-new">New ticket</button></header>
      <div id="gd-support-form" class="gd-support-form" hidden><div class="gd-support-grid">
        <label>Category<select id="gd-support-category"><?php foreach(gd_client_portal_support_categories() as $k=>$v): ?><option value="<?php echo esc_attr($k); ?>"><?php echo esc_html($v); ?></option><?php endforeach; ?></select></label>
        <label>Priority<select id="gd-support-priority"><?php foreach(gd_client_portal_support_priorities() as $k=>$v): ?><option value="<?php echo esc_attr($k); ?>" <?php selected($k,'normal'); ?>><?php echo esc_html($v); ?></option><?php endforeach; ?></select></label>
      </div><label>Subject<input id="gd-support-subject" maxlength="255"></label><label>Message<textarea id="gd-support-body" rows="5"></textarea></label><label>Project ID (optional)<input id="gd-support-project" type="number" min="0" value="0"></label><button type="button" id="gd-support-create">Submit ticket</button> <span id="gd-support-result"></span></div>
      <div class="gd-support-layout"><section><h3>Your tickets</h3>
      <?php if(!$tickets): ?><div class="gd-support-empty">No support tickets yet.</div><?php endif; ?>
      <?php foreach($tickets as $t): ?><a class="gd-support-ticket<?php echo $ticket_id===(int)$t->id?' is-active':''; ?>" href="?support_ticket=<?php echo intval($t->id); ?>"><div><strong><?php echo esc_html($t->subject); ?></strong><span class="gd-support-status"><?php echo esc_html(gd_client_portal_support_statuses()[$t->status]??$t->status); ?></span></div><small>#<?php echo intval($t->id); ?> · <?php echo esc_html(ucfirst($t->priority)); ?> · <?php echo esc_html(wp_date(get_option('date_format'),strtotime($t->updated_at))); ?></small></a><?php endforeach; ?>
      </section><section class="gd-support-thread">
      <?php if($ticket_id): $t=gd_client_portal_support_ticket($ticket_id); if($t&&gd_client_portal_support_access($t)): ?>
        <div class="gd-support-thread-head"><div><span>Ticket #<?php echo intval($t->id); ?></span><h3><?php echo esc_html($t->subject); ?></h3></div><span class="gd-support-status"><?php echo esc_html(gd_client_portal_support_statuses()[$t->status]??$t->status); ?></span></div>
        <div class="gd-support-messages"><?php foreach(gd_client_portal_support_messages($t->id) as $m): $u=gd_client_portal_cached_user($m->author_id); ?><article class="gd-support-message"><strong><?php echo esc_html($u?$u->display_name:'User'); ?></strong><time><?php echo esc_html(wp_date(get_option('date_format').' H:i',strtotime($m->created_at))); ?></time><p><?php echo nl2br(esc_html($m->body)); ?></p></article><?php endforeach; ?></div>
        <div class="gd-support-reply"><textarea id="gd-support-reply" rows="4" placeholder="Write a reply…"></textarea><button type="button" id="gd-support-send" data-ticket="<?php echo intval($t->id); ?>">Send reply</button> <span id="gd-support-reply-result"></span></div>
      <?php else: ?><div class="gd-support-empty">Select a ticket to view the conversation.</div><?php endif; else: ?><div class="gd-support-empty">Select a ticket to view the conversation.</div><?php endif; ?>
      </section></div>
    </div>
    <?php return ob_get_clean();
}
add_shortcode('gd_support_tickets','gd_client_portal_render_support');add_shortcode('gd_helpdesk','gd_client_portal_render_support');
function gd_client_portal_support_admin(){
    gd_client_portal_enqueue_support_assets(true);
    if(!current_user_can('gd_client_portal_access_admin'))wp_die('Access denied.');$rows=gd_client_portal_support_tickets(300);echo '<div class="wrap gd-support-admin"><h1>Support & Helpdesk</h1><p>Manage tenant-scoped support tickets, SLAs and client responses.</p><table class="widefat striped"><thead><tr><th>Ticket</th><th>Client</th><th>Project</th><th>Priority</th><th>Status</th><th>Assignment / SLA</th></tr></thead><tbody>';foreach($rows as $t){$u=gd_client_portal_cached_user($t->user_id);echo '<tr><td><strong>#'.intval($t->id).' '.esc_html($t->subject).'</strong><br><small>'.esc_html(ucfirst($t->category)).'</small></td><td>'.esc_html($u?$u->display_name:'User #'.$t->user_id).'</td><td>'.($t->project_id?'#'.intval($t->project_id):'General').'</td><td>'.esc_html(ucfirst($t->priority)).'</td><td><select class="gd-support-admin-status" data-id="'.intval($t->id).'">';foreach(gd_client_portal_support_statuses() as $k=>$v)echo '<option value="'.esc_attr($k).'" '.selected($t->status,$k,false).'>'.esc_html($v).'</option>';echo '</select></td><td><input class="gd-support-admin-assignee" data-id="'.intval($t->id).'" type="number" min="0" value="'.intval($t->assigned_to).'" placeholder="User ID"><br><small>Due: '.esc_html($t->due_at?:'—').'</small><button type="button" class="button gd-support-admin-save" data-id="'.intval($t->id).'">Save</button></td></tr>';}if(!$rows)echo '<tr><td colspan="6">No tickets.</td></tr>';echo '</tbody></table></div>';}
add_action('admin_menu',function(){add_submenu_page('gd-client-portal','Support & Helpdesk','Support & Helpdesk','gd_client_portal_access_admin','gd-client-portal-support','gd_client_portal_support_admin');},20);
function gd_client_portal_support_assets(){
    wp_register_style('gd-client-portal-support',GD_CLIENT_PORTAL_URL.'assets/support.css',array('gd-client-portal'),GD_CLIENT_PORTAL_VERSION);
    wp_register_script('gd-client-portal-support',GD_CLIENT_PORTAL_URL.'assets/support.js',array(),GD_CLIENT_PORTAL_VERSION,true);
}
add_action('wp_enqueue_scripts','gd_client_portal_support_assets');
add_action('admin_enqueue_scripts','gd_client_portal_support_assets');

function gd_client_portal_enqueue_support_assets($admin=false){
    if(!is_user_logged_in()) return;
    wp_enqueue_style('gd-client-portal-support');
    wp_enqueue_script('gd-client-portal-support');
    wp_localize_script('gd-client-portal-support','GDClientSupport',array(
        'ajax_url'=>admin_url('admin-ajax.php'),
        'nonce'=>wp_create_nonce('gd_client_portal_support'),
        'admin_nonce'=>wp_create_nonce('gd_client_portal_support_admin'),
    ));
}

add_action('init',function(){if(function_exists('gd_client_portal_register_dashboard_view'))gd_client_portal_register_dashboard_view('support','gd_client_portal_render_support');});
function gd_client_portal_support_escalation(){$now=current_time('mysql');$rows=gd_client_portal_support_repository()->overdue($now,100);foreach($rows as $ticket){gd_client_portal_support_service()->escalate($ticket);if(function_exists('gd_client_portal_create_notification')){gd_client_portal_create_notification($ticket->user_id,'Support ticket SLA escalation',$ticket->subject,'support_ticket',$ticket->project_id,$ticket->tenant_id,'support_'.$ticket->id.'_'.md5((string)$ticket->due_at));foreach(gd_client_portal_support_managers($ticket->tenant_id) as $uid)gd_client_portal_create_notification($uid,'Support SLA escalation',$ticket->subject,'support_ticket',$ticket->project_id,$ticket->tenant_id,'support_'.$ticket->id.'_'.md5((string)$ticket->due_at));}if(function_exists('gd_client_portal_audit_log'))gd_client_portal_audit_log('support_sla_escalation',$ticket->subject,$ticket->project_id,$ticket->tenant_id,'','support_ticket',$ticket->id,array('priority'=>'urgent'));}}
add_action('gd_client_portal_sla_daily','gd_client_portal_support_escalation');